### ISSUE TITLE
SLF4J Love

### ISSUE THREAD

**Issue by darkfrog26** [outr/scribe#100]
The integration for SLF4J could use a bit more TLC to make it cleaner to use and better functionality for output.

**Comment by olafurpg** [comment]
One nice improvements would be to expose the underlying slf4j logger name, `record.className` seems hardcoded to `scribe.slf4j.ScribeLoggerAdapter` at the moment.

**Comment by darkfrog26** [comment]
Yeah, this used to not be a problem, but for some reason, it got screwed up along the way.
