### ISSUE TITLE
rolling logger doesn't work as expected when logging to an existing old file which needs to roll at first logging

### ISSUE THREAD

**Issue by andreak** [outr/scribe#103]
Configure logging like this
```
        scribe.Logger.root
        .clearHandlers()
        .clearModifiers()
        .withHandler(minimumLevel = Some(Level.Trace)
            , writer = FileWriter()
                       .path(_ => Paths.get(System.getProperty("user.home"),"logs", "trace.log"))
                       .rolling(LogPath.daily(prefix = "trace.log"
                           , directory = Paths.get(System.getProperty("user.home"), "logs"))
                       ).autoFlush
        )
        .replace()
        debug("Logging in old file")
```

I expected that a pre-existing, several days old, file called "trace.log" should be renamed "trace-[date].log", but logging continues to log to the old file, without rolling.

```
$ cat /dev/null > ~/logs/trace.log
$ touch -d "2 days ago" ~/logs/trace.log
$ stat ~/logs/trace.log
  File: /home/andreak/logs/trace.log
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: fd05h/64773d    Inode: 94768165    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/ andreak)   Gid: ( 1000/ andreak)
Access: 2019-01-06 00:30:34.260593691 +0100
Modify: 2019-01-06 00:30:34.260593691 +0100
Change: 2019-01-08 00:30:34.257023477 +0100
 Birth: -
$ tail -f ~/logs/trace.log
2019.01.08 00:30:43 DEBUG Test:41:22 - Logging in old file
```

**Comment by darkfrog26** [comment]
Sorry for the late response on this. I forgot that I never responded.  Any chance you've had a chance to dig into the code and perhaps find the problem yourself? :)

If not, I'll try to get a look into this soon.

**Comment by andreak** [comment]
Still happens, and I don't have enough understanding of the code to see why...

**Comment by darkfrog26** [comment]
I'll try to get this and #107 resolved this week. Thanks for your patience.

**Comment by darkfrog26** [comment]
@andreak, this should be fixed now and I'll try to do a new release today.

**Comment by darkfrog26** [comment]
Sorry this took so crazy long.

**Comment by andreak** [comment]
Rock on!

**Comment by darkfrog26** [comment]
I tried to replicate your test case here: https://github.com/outr/scribe/blob/master/core/jvm/src/test/scala/spec/FileLoggingSpec.scala#L197

I'm publishing 2.7.4 now, so please let me know if you any problems going forward.
