### ISSUE TITLE
Extend Abbreviator to support abbreviateClassName: Boolean

### ISSUE THREAD

**Issue by andreak** [outr/scribe#104]
It'd be nice if we had this signature in Abbreviator:
```
  def apply(value: String,
            maxLength: Int,
            separator: Char = '.',
            removeEntries: Boolean = true,
            abbreviateClassName: Boolean = false,
            abbreviateName: Boolean = false): String
```

...such that only package-names are shortened, preventing the ClassName from getting garbeled in the logs. I actually find ClassName much more important than method-name (as the line-number implies that). #

**Comment by darkfrog26** [comment]
This should be resolved with 2.7.2. Please let me know if you have any further issues.
