### ISSUE TITLE
Native log4cats implementation

### ISSUE THREAD

**Issue by Daenyth** [outr/scribe#105]
I'd like to see an alternate scribe class with native log4cats support. The `log4cats-scribe` package exists and works, but it has the drawback of recording incorrect `Position` information, because the logger is defined as a class wrapping around `Sync[F].delay(logger.foo(..))`. This causes the position reporting to be marked as the wrapper class rather than the class doing the logging, for example `io.chrisdavenport.log4cats.scribe.ScribeLogger.$anon.info:24:32`

From reading the `Macros` code, it should be possible to implement a new `ScribeLogger[F]` class with minor modification; where the `Macros.log` method currently emits
```scala
    q"""
       $logger.log(_root_.scribe.LogRecord[$m](
        /* stuff */
       ))
     """
```
it could instead emit something like:
```scala
    q"""
       Sync[F].delay($logger.log(_root_.scribe.LogRecord[$m](
        /* stuff */
       )))
     """
```

**Comment by darkfrog26** [comment]
Do you have a link to `log4cats-scribe`?

**Comment by Daenyth** [comment]
https://github.com/ChristopherDavenport/log4cats/blob/master/cats/scribe/shared/src/main/scala/io/chrisdavenport/log4cats/scribe/ScribeLogger.scala

**Comment by darkfrog26** [comment]
@Daenyth, why wouldn't you just do this in that project?  Use your own Macro instead and it should accomplish the same goal, right?

**Comment by Daenyth** [comment]
I wasn't sure the best project to report it in - if you think it's better there, I'll ticket it on that repo

**Comment by darkfrog26** [comment]
Since there is no dependency in Scribe to Cats, it makes sense for that to occur there.

**Comment by Daenyth** [comment]
Is it possible to reuse the rest of the macros from another project, in that case? Or would it have to be a from-scratch copy/paste implementation. My main concern in making it external is if the macros change over time, then those changes would have to be manually re-applied to the downstream app.

**Comment by darkfrog26** [comment]
Yes, the Macros in Scribe can be utilized from external projects like log4cats-scribe

**Comment by Daenyth** [comment]
Would it be possible to split `scribe.Macros` into a `trait Macros` that contains the current definitions, plus a `object Macros extends Macros`? To do the behavior I want, I need to either override the `Macros.log` macro, or I need to find some way to wrap the existing macros such that I can override `LoggerSupport` instead, and where it currently has things like `macro Macros.autoLevel1[M]`, change it to instead be `macro MyMacro.wrapInSyncFDelay[F](Macros.autoLevel1[M])`.

I'm not familiar with writing macros; splitting the `Macros` object into a trait I can override would be much easier for me to implement. If that's not practical, is the `LoggerSupport` method possible to do? It looks like I will need to re-implement much of the functionality in `scribe.Logger` either way

**Comment by darkfrog26** [comment]
I think `log4cats` is WAY more complicated than it needs to be.  You can just create a custom `LogHandler` to call `Sync[F].delay(SynchronousLogHandler.log(this, record))` (see: https://github.com/outr/scribe/blob/544886b43624acd7801461abbad2701e1828d644/core/jvm/src/main/scala/scribe/handler/AsynchronousLogHandler.scala for an example use-case).

You shouldn't need any Macros or other customization.

**Comment by Daenyth** [comment]
I'm not sure how that would work - I need `scribeCatsLogger.info` (for example) to return `F[Unit]`, and regardless of the `LogHandler`s on the logger, `scribe.Logger#info` returns `Unit`. Constructing an `IO[Unit]` or similar and then *not* threading it into your `flatMap` chain will just result in the `IO` never being executed. How can I call `scribeLogger.info` and get the `IO[Unit]` out of the LogHandler?

**Comment by darkfrog26** [comment]
Ah, so you're attempting to chain together calls so they are invoked in sequence, but asynchronously?

**Comment by Daenyth** [comment]
They aren't necessarily asynchronous, they just need to be suspended via the `Sync[F].delay(a: => A): F[A]` method

**Comment by darkfrog26** [comment]
Then why not just have them be invoked inside `delay`, like: `Sync[F].delay(scribe.info("Hello, World!"))`?

**Comment by Daenyth** [comment]
That's one approach, but at that point you're no longer using the `Logger[F]` interface, and you're mixing in implementation details - other loggers can't be swapped in. Not to mention it's considerably longer than just calling `log.info` or `Logger[F].info`

**Comment by darkfrog26** [comment]
Okay, so just write a Macro that does exactly that. Let me know if you need help doing that, but it's pretty trivial.

**Comment by zchbndcc9** [comment]
What needs to be done for this? I'd love to take a crack at it since I could really use it.

**Comment by Daenyth** [comment]
I think it's likely best to maintain by making a module that depends on log4cats-core, and adapting the existing macro to return `F[Unit]` via `Sync[F].delay(existingLoggerThings.info(...))`.

If you can write a macro that transforms the existing call by just wrapping it in `Sync[F].delay` then a lot of code could be reused.

**Comment by darkfrog26** [comment]
Happy to help if I can, but I don't use log4cats, so it's a bit out of my element.

**Comment by Daenyth** [comment]
It would consist of implementing the `Logger[F]` interface:

<details>
<summary>Logger</summary>

```scala
trait Logger[F[_]] extends MessageLogger[F] with ErrorLogger[F]

trait ErrorLogger[F[_]]{
  def error(t: Throwable)(message: => String): F[Unit]
  def warn(t: Throwable)(message: => String): F[Unit]
  def info(t: Throwable)(message: => String): F[Unit]
  def debug(t: Throwable)(message: => String): F[Unit]
  def trace(t: Throwable)(message: => String): F[Unit]
}

trait MessageLogger[F[_]]{
  def error(message: => String): F[Unit]
  def warn(message: => String): F[Unit]
  def info(message: => String): F[Unit]
  def debug(message: => String): F[Unit]
  def trace(message: => String): F[Unit]
}
```

</details>

The implementation would be to wrap [`Macros.log`](https://github.com/outr/scribe/blob/master/core/shared/src/main/scala/scribe/Macros.scala#L48) such that it emits 
```scala
_root_.cats.effect.Sync[F].delay($logger.log(...))
```

**Comment by Daenyth** [comment]
See also slf4j macros: https://github.com/ChristopherDavenport/log4cats/blob/f5c7256e73af675154f39de140f6fc08c0a73be5/slf4j/src/main/scala/io/chrisdavenport/log4cats/slf4j/internal/LoggerMacros.scala#L60-L67

**Comment by zchbndcc9** [comment]
> It would consist of implementing the `Logger[F]` interface:
> 
> `Logger[F]`
> ```scala
> trait Logger[F[_]] extends MessageLogger[F] with ErrorLogger[F]
> 
> trait ErrorLogger[F[_]]{
>   def error(t: Throwable)(message: => String): F[Unit]
>   def warn(t: Throwable)(message: => String): F[Unit]
>   def info(t: Throwable)(message: => String): F[Unit]
>   def debug(t: Throwable)(message: => String): F[Unit]
>   def trace(t: Throwable)(message: => String): F[Unit]
> }
> 
> trait MessageLogger[F[_]]{
>   def error(message: => String): F[Unit]
>   def warn(message: => String): F[Unit]
>   def info(message: => String): F[Unit]
>   def debug(message: => String): F[Unit]
>   def trace(message: => String): F[Unit]
> }
> ```
> 
> The implementation would be to wrap [`Macros.log`](https://github.com/outr/scribe/blob/master/core/shared/src/main/scala/scribe/Macros.scala#L48) such that it emits
> 
> ```scala
> _root_.cats.effect.Sync[F].delay($logger.log(...))
> ```

Would you care explaining what you mean by this? I can't just wrap the `$logger.log(...)` in the Sync monad?

**Comment by darkfrog26** [comment]
You should be able to in a Macro, but you can't do it directly or else all of the derived trace information will always point to your code instead of the line that called your code to create the log record.

**Comment by Daenyth** [comment]
As darkfrog says; if you do `Sync[F].delay(log...)` then the macro will generate `ScribeLogger.scala:123` for every invocation instead of the class calling the log method. That behavior was the impetus for me opening this ticket.

**Comment by darkfrog26** [comment]
FYI, because Scribe now uses Sourcecode, this should be completely manageable without any changes to Scribe.

**Comment by darkfrog26** [comment]
This is now fully integrated and will be released with Scala 3.7

**Comment by benhutchison** [comment]
I just want to note for others, because it took me a while to figure out, there isnt yet AFAICT an impl of the log4cats `Logger` trait backed by Scribe (like eg this [JS Console one](https://github.com/typelevel/log4cats/blob/main/js-console/src/main/scala/org/typelevel/log4cats/console/ConsoleLogger.scala)). Rather there's the building blocks in terms of Cats Effect.

**Comment by nkgm** [comment]
Thanks for the heads up @benhutchison . I've been looking for a `log4cats` implementation to use in my Scala.js projects. Any idea on the amount of effort required to build it out of the provided blocks?

**Comment by benhutchison** [comment]
I think it's a pretty straightforward paint by numbers (or is it
by-types?), fill out of the Logger traits abstract methods. But obviously
it needs to take a dependency on both scribe and log4cats, and there isn't
currently a location in either project that has that.

**Comment by nkgm** [comment]
> But obviously it needs to take a dependency on both scribe and log4cats, and there isn't currently a location in either project that has that.

Can you elaborate? If you mean where the artifact should live, then it would make more sense to be published under `log4cats`. There even used to be a [log4cats-scribe](https://index.scala-lang.org/typelevel/log4cats/artifacts/log4cats-scribe) artifact which was removed in [this commit](https://github.com/typelevel/log4cats/commit/77ea7297e33446dd6901f91ab074e21329b23537) along with every other integration, so I guess it's not happening, but can always publish standalone.

Having said that, [the actual implementation previously removed](https://github.com/typelevel/log4cats/blob/f8d54a78ad91a822f15d4f88612a435a99e761cf/cats/scribe/shared/src/main/scala/io/chrisdavenport/log4cats/scribe/ScribeLogger.scala) seems trivial, so it can just be another bit of boilerplate you tailor to each project.

**Comment by benhutchison** [comment]
Yeah log4cats would just need to create a submodule with dependency on
scribe

**Comment by darkfrog26** [comment]
You could just use `scribe-cats` instead? See the spec for example usage: https://github.com/outr/scribe/blob/master/cats/shared/src/test/scala/spec/ScribeSpec.scala

**Comment by darkfrog26** [comment]
How I typically use it is like:
```scala
      import scribe.cats.{io => logger}
      logger.info("Example") // IO[Unit]
```
