### ISSUE TITLE
Log-level package granularity

### ISSUE THREAD

**Issue by waiter-melon** [outr/scribe#107]
Hi everyone,

Is there any easy way to choose a certain log level for any logger within a particular package?

Similar to what we do with Logback: `<logger name="org.apache.flink.api" level="WARN"/>`

Thanks,

**Comment by darkfrog26** [comment]
Can you clarify what you mean?  Does that make anything logged in that package automatically set to WARN?

**Comment by waiter-melon** [comment]
Nope. That setting states: in that package, logs with log-level **<** than WARN get filtered out (so only WARN and above, ERROR etc.).

**Comment by darkfrog26** [comment]
You could use `LevelFilter` to do that:
```scala
import scribe._
logger.withModifier(LevelFilter >= Level.Warn).replace()
```
You can do that per-class, but there's not really good default package level handling built-in, although it would be pretty easily accomplished:
```scala
Logger.root.withModifier(new LogModifier {
    override def priority: Priority = Priority.Normal

    override def apply[M](record: LogRecord[M]): Option[LogRecord[M]] = if (record.className.startsWith("org.apache.flink.api") && record.level < Level.Warn) {
      None
    } else {
      Some(record)
    }
  }).replace()
```
If you're interested in creating a more generic solution and contributing it back as a PR it would be welcome. ;)

**Comment by waiter-melon** [comment]
Thank you @darkfrog26 for the workaround. 
I'll be working on providing a more elegant way to do this if I get some time.

**Comment by andreak** [comment]
I asked about this here: https://gitter.im/outr/scribe?at=5c33bcfa12db9607e7509b61
It would really benefit users migrating from other logging-frameworks commonly used in JAVA-ecosystems.

**Comment by darkfrog26** [comment]
What do you guys think of something like this:

```scala
Logger.root.withModifier(
  FilterBuilder.select.packageName.startsWith("org.apache.flink.api").exclude.level(_ < Level.Warn)
)
```

I haven't finished modeling this out, but it would be more of a builder pattern to define filtering.

**Comment by darkfrog26** [comment]
Perhaps a more DSL approach may be better?

```scala
Logger.root.withModifier(
  select(packageName.startsWith("org.apache.flink.api").exclude(level < Level.Warn)
)
```

**Comment by darkfrog26** [comment]
How does this look? https://github.com/outr/scribe/blob/FilterBuilder/core/shared/src/test/scala/specs/LoggingSpec.scala#L216

**Comment by rlebran** [comment]
Looks good but what if we want to log with a lower log level for the given package, will it work with this modelisation ? 
i.e.: `org.apache.flink.api` with a log level set to DEBUG and the global log level set to INFO.

**Comment by waiter-melon** [comment]
Maybe we should go for a _path-based_ selection rather than _package-based_. In fact, we should be able to specify down to a single class (`org.apache.flink.api.AnyClass`).

**Comment by andreak** [comment]
One should definitely be able to specify down to a single class.

**Comment by darkfrog26** [comment]
@rlebran, how about this:

This will set anything with the package of "org.apache.flink.api" to `Level.Debug`
```scala
select(packageName("org.apache.flink.api")).setLevel(Level.Debug)
```

This will boost anything under the "org.apache.flink.api" by one level:
```scala
select(packageName.startsWith("org.apache.flink.api")).boostOneLevel
```

@waiter-melon, you can do that with this:
```scala
select(className("org.apache.flink.api.AnyClass")).include(level >= Level.Debug)
```

The DSL is pretty flexible and we can continue to expand it as we encounter more scenarios we want to support.

**Comment by darkfrog26** [comment]
Unless there are other suggestions, I'll close this ticket and the functionality will release with `2.7.4`.

**Comment by ngbinh** [comment]
looks awesome!

**Comment by darkfrog26** [comment]
2.7.4 is released

**Comment by andreak** [comment]
Regarding classname-filters; I found that your example with:
```select(className("org.apache.flink.api.AnyClass")).include(level >= Level.Debug)```
didn't work and I had to use ```ClassNameFilter```, like this:
```select(ClassNameFilter("org.apache.flink.api.AnyClass")).include(filterLevel >= Level.Debug)```
Maybe worth documenting...

**Comment by darkfrog26** [comment]
Yeah, sorry, that was a mistake on my part. I've added it to the DSL and it will go in the next release: https://github.com/outr/scribe/commit/8448bda41da2c31ea5134ed58725d575a6d03a3a

**Comment by avernet** [comment]
I'd like to filter by class name, so only to see messages logged by specific classes. I'm seeing what seem to be elements for doing so in this thread, but may I ask where this is documented? (It is not even clear to me what I should import to use the `select` I see some of the above snippets.)

**Comment by andreak** [comment]
Here's my complete logging-config, hope it helps you:

Use like this:
```scala
String moduleName = "email-import";
LoggerInit.apply(moduleName);
```
```scala
package com.visena.application.main.logging

import java.nio.file.Paths

import io.milton.http.StandardFilter
import no.officenet.origo.core.infrastructure.Constants
import scribe.{Level, Logger, Priority}
import scribe.filter.{level => filterLevel, _}
import scribe.format.{Formatter, FormatterInterpolator, date, level, mdc, message, position, threadName}
import scribe.handler.LogHandler
import scribe.writer.{ConsoleWriter, FileWriter}
import scribe.writer.file.LogPath

object LoggerInit {

	val mdcFormatter: Formatter = formatter"$date [$threadName] [${mdc(Constants.LOG_MDC_USERNAME_KEY)}] [${mdc(Constants.LOG_MDC_REQUEST_KEY)}] $level $position - $message"
	def apply(moduleName: String) {

		val consoleHandler = LogHandler(minimumLevel = Some(Level.Info), writer = ConsoleWriter)

		val traceHandler = LogHandler(
			minimumLevel = Some(Level.Info)
			, writer = FileWriter()
				.path(_ => Paths.get(System.getProperty("user.home"),"visena", "logs", moduleName, "visena-trace.log"))
				.rolling(LogPath.daily(prefix = "visena-trace", directory = Paths.get(System.getProperty("user.home")
					, "visena", "logs", moduleName)))
				.autoFlush
			, formatter = mdcFormatter
		).withModifier(
			select(
				packageName.startsWith("no.officenet"),
				packageName.startsWith("com.visena")
			).boosted(Level.Trace, Level.Info).priority(Priority.Important)
		).withModifier(
			select(
				className(classOf[StandardFilter].getName)
			).include(filterLevel >= Level.Error)
		)

		val warnHandler = LogHandler(
			minimumLevel = Some(Level.Warn),
			writer = FileWriter()
				.path(_ => Paths.get(System.getProperty("user.home"),"visena", "logs", moduleName, "visena-warn.log"))
				.rolling(LogPath.daily(prefix = "visena-warn", directory = Paths.get(System.getProperty("user.home")
					, "visena", "logs", moduleName)))
				.autoFlush
			, formatter = mdcFormatter
		).withModifier(
			select(
				packageName.startsWith("no.officenet"),
				packageName.startsWith("com.visena")
			).exclude(filterLevel > Level.Warn).excludeUnselected
		)

		val errorHandler = LogHandler(
			minimumLevel = Some(Level.Error),
			writer = FileWriter()
				.path(_ => Paths.get(System.getProperty("user.home"),"visena", "logs", moduleName, "error.log"))
				.rolling(LogPath.daily(prefix = "error", directory = Paths.get(System.getProperty("user.home")
					, "visena", "logs", moduleName)))
				.autoFlush
			, formatter = mdcFormatter
		)

		Logger.root
			.clearHandlers()
			.clearModifiers()
			.withHandler(consoleHandler)
			.withHandler(traceHandler)
			.withHandler(warnHandler)
			.withHandler(errorHandler)
			.replace()

		scribe.Logger("SERVICETIMELOGGER")
			.orphan()
			.clearHandlers()
			.clearModifiers()
			.withHandler(minimumLevel = Some(Level.Info)
				, writer = FileWriter()
					.path(_ => Paths.get(System.getProperty("user.home"),"visena", "logs", moduleName, "visena-performance.log"))
					.rolling(LogPath.daily(prefix = "visena-performance", directory = Paths.get(System.getProperty("user.home")
						, "visena", "logs", moduleName)))
					.autoFlush
				, formatter = mdcFormatter
			)
			.replace()

	}
}
```

The constants Constants are:
```scala
val LOG_MDC_USERNAME_KEY: String = "userName"
val LOG_MDC_REQUEST_KEY: String = "requestKey"
```
Then these are set in the begining of a web-request:
```scala
//  These are evaluated by name, so materialize the values first
MDC(Constants.LOG_MDC_USERNAME_KEY) = userName
MDC(Constants.LOG_MDC_REQUEST_KEY) = requestKey
```
