### ISSUE TITLE
Log message is evaluated multiple times

### ISSUE THREAD

**Issue by rmgk** [outr/scribe#108]
Code in the logging message is evaluated twice in the default config:
```scala
var i = 0
def sideEffect(): String = {
  i = i + 1
  i.toString
}

scribe.info(sideEffect())
// prints “2”
```
While side effects in a logging call may be a terrible idea, this is quite awkward when logging some expensive call.

**Comment by darkfrog26** [comment]
Interesting, and a good catch.  I'll look into this.

**Comment by darkfrog26** [comment]
@rmgk, this will go out in the next release (2.7.4)
