### ISSUE TITLE
StaticMDCBinder Warning

### ISSUE THREAD

**Issue by darkfrog26** [outr/scribe#11]
`SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder". SLF4J: Defaulting to no-operation MDCAdapter implementation. SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.`

See: https://github.com/qos-ch/slf4j/blob/master/slf4j-nop/src/main/java/org/slf4j/nop/NOPMDCAdapter.java

**Comment by darkfrog26** [comment]
I'm not sure I agree with the ideology behind MDC. Moving this out of 2.0 until a valid reason can be given to support it.

**Comment by darkfrog26** [comment]
There are better ways to manage this with logging. Closing ticket.

**Comment by andreak** [comment]
For the archives; The lack of MDC makes Scribe unsuitable for our application which requires logging stuff in a way MDC facilitates.

**Comment by darkfrog26** [comment]
@andreak, do you care about thread-safety?  Does it matter if it is a proper MDC implementation (for SLF4J integration) or a better solution that provides the same functionality?

**Comment by andreak** [comment]
If by thread-safety you mean that the values of MDC-properties are thread-local only and never change for the lifetime of the thread then yes. Mind you that many webservers use a threadpool for handling HTTP-requests, hence reusing threads, so it's important to be able to "install" and "clear" the values of the "current-thread"'s MDC-properties. This is usually done in ServletFilters.

It's hard to tell if compatibility with SLF4J/Log4J matters before I get to try it with MDC-ish support. We use lots of 3rd-party libs (and have som legacy JAVA-code) which use Log4J (configured thru log4j.xml) and it'd be cool not to have separate log-files for parts logging with Scribe and legacy-style.

**Comment by darkfrog26** [comment]
@andreak take a look at https://github.com/outr/scribe/commit/c52857f9e727b2108d020d30c131d92eee8a9023 and let me know if this fulfills your requirements

It provides a proper implementation of SLF4J's MDC support while also providing a cleaner interface for use in Scala directly.

**Comment by darkfrog26** [comment]
Specifically, take a look at the test for an example of usage: https://github.com/outr/scribe/commit/c52857f9e727b2108d020d30c131d92eee8a9023#diff-827f41ef68e5c0de3e996f25ceedc051R97

**Comment by andreak** [comment]
Looks great, will try it!

**Comment by darkfrog26** [comment]
@andreak please confirm after you've had a look and I'll roll it out in 2.3.4 as it has no breaking changes

**Comment by andreak** [comment]
I'm not able to compile scribe:
```
sbt:scribe> compile
[info] Compiling 5 Scala sources to /home/andreak/dev/scribe/slf4j/target/scala-2.12/classes ...
[error] /home/andreak/dev/scribe/slf4j/src/main/scala/scribe/slf4j/ScribeMDCAdapter.scala:10:60: missing argument list for method update in object MDC
[error] Unapplied methods are only converted to functions when a function type is expected.
[error] You can make this conversion explicit by writing `update _` or `update(_,_)` instead of `update`.
[error]   override def put(key: String, `val`: String): Unit = MDC.update(key) = `val`
[error]                                                            ^
[error] one error found
[error] (slf4j / Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed 27.apr.2018 10:48:45
```

When I import the project in IDEA I get undefined import scribe.MDC, it seems the slf4j module somehow is not dependent on core.

**Comment by darkfrog26** [comment]
Sorry about that.  In my rush to knock this out, I didn't properly test it.  If you update the project it should work now.

**Comment by andreak** [comment]
Thanks, got it to build now. I'll spend some time this weekend integrating it with our application and see how it works. I'll report back.

**Comment by darkfrog26** [comment]
@andreak drop me a message on Scribe's Gitter channel if you run into any problems and I'll respond when I can.

**Comment by andreak** [comment]
Ok, thanks.

**Comment by darkfrog26** [comment]
@andreak any updates on this?

**Comment by andreak** [comment]
I posted a question on the Gitter channel:-) That will allow me to use Scribe without too much manual refactoring.

**Comment by andreak** [comment]
The MDC-part is confirmed to work OK.
