### ISSUE TITLE
Scala 2.13.0 compatible release

### ISSUE THREAD

**Issue by rachitnigam** [outr/scribe#114]
Wondering what needs to be done for a 2.13.0 release and if there is something I can help with to make this happen.

**Comment by darkfrog26** [comment]
The issues I ran into when trying to work toward this was problems with Circe's Scala.js in 2.13.  I need to spend some more time investigating.

**Comment by darkfrog26** [comment]
Just released Scribe 2.7.8 with Scala 2.13 support. Note: this release doesn't include 2.13 support for `scribe-slack` or `scribe-logstash` because they have a cyclical dependency that won't be resolved until 2.7.9.

**Comment by rachitnigam** [comment]
Awesome! Thanks a lot!
