### ISSUE TITLE
Documentation on Handlers and Modifiers

### ISSUE THREAD

**Issue by zchbndcc9** [outr/scribe#116]
It would be very nice if there was some more documentation on handlers and modifications and how to utilize them / create your own.

**Comment by darkfrog26** [comment]
I agree, and that's an item on my agenda, but if you'd be interested in contributing I'd be happy to answer any questions.  Unfortunately, right now my time is incredibly limited.

**Comment by zchbndcc9** [comment]
I am right there with you on the time constraints. I would love to but my plate is also very full ATM

**Comment by darkfrog26** [comment]
I've added some docs to `LogHandler` and `LogModifier` to hopefully make its usage more clear.
