### ISSUE TITLE
Tagging of logs

### ISSUE THREAD

**Issue by fdietze** [outr/scribe#117]
Very often I find that log levels are not enough. If I set the loglevel to debug. I'm seeing way too many logs that I'm not interested in. My use-case is with ScalaJS in the frontend where I have debug-logging for drag-and-drop, event handling, state, api requests etc.
I would like to somehow tag my logging such that only the tags that are activated are logged. For example, to debug something I only want to see the logs related to drag-and-drop and state.
It should be possible for one log to belong to multiple tags.

Is this somehow possible already?

Syntax could look like this:

```scala
scribe.debug("a drag that changed the state", tags = List("drag", "state"))
```

Maybe not even encode tags as strings but as ADT / case objects?

**Comment by darkfrog26** [comment]
It wouldn't be too difficult to add such support, but there are a few other ways to handle this already.  Personally, I would create custom `Loggable` types to represent the different types of messages and create filtering based on that.  If that's not sufficient, I'd happily welcome tags.

**Comment by darkfrog26** [comment]
Actually, it just occurred to me that tags already actually exist with MDC.  Please re-open if there is something that you can't do with MDC.

**Comment by fdietze** [comment]
Thanks, I'll have a closer look.
