### ISSUE TITLE
Don't put full file name in logging initialisation

### ISSUE THREAD

**Issue by Bathtor** [outr/scribe#118]
Hi, 

I noticed that the logging macros put the absolute path of the source file for every position into the logging record, which I believe happens here:
https://github.com/outr/scribe/blob/951b94a2c3514db130cd78059a891db4c0c6054a/core/shared/src/main/scala/scribe/Macros.scala#L67

I would like to request to instead only put a **relative path** from the **project root**.

The reason for this request is, that I recently noticed that some of my local filesystem paths show up on Google search, which worried me a bit, until I realised it is because they appear in logging statements in my ScalaJS generated Javascript code (search for `EPCompendium.scala` in the source [here](https://eptools.lkroll.com/) to see what I mean). It's not a huge issue, but I'd rather they not be there.

Alternatively, simply removing file paths from fullOptJS builds would probably also work well.

Cheers,
Lars

**Comment by darkfrog26** [comment]
That's a good suggestion.  I'll try to get this added in the next release.

**Comment by darkfrog26** [comment]
Sorry for taking so long on this, but it will go out in 2.8.  FYI, this will now only contain the file's name, no path at all since you can get the package from `className`.

**Comment by darkfrog26** [comment]
2.8.0 is now released
