### ISSUE TITLE
Inconsistent handler minimumLevel behavior

### ISSUE THREAD

**Issue by david-bouyssie** [outr/scribe#120]
I'm trying to change the default minimum logging level in a Scala Native library.
I started with these lines of code:

```scala
scribe.Logger.root.clearHandlers().clearModifiers().withHandler(
  minimumLevel = scribeMinLogLevelOpt
)
```

but it doesn't work as expected.

So I ended up with this more complicated solution:
```scala
    val logger = scribe.Logger.root.clearHandlers().clearModifiers().withHandler(
      minimumLevel = scribeMinLogLevelOpt
    )
    if (scribeMinLogLevelOpt.isDefined) {
      logger.withModifier(
        select(packageName.startsWith(namespace))
          .exclude(level < scribeMinLogLevelOpt.get)
          .priority(Priority.High)
      ).replace()
    } else {
      logger.withModifier(
        select(packageName.startsWith(namespace))
          .exclude(level <= Level.Error)
          .priority(Priority.High)
      ).replace()
    }
```

It works but I don't understand why the first solution doesn't behave the same.
Maybe I missed something regarding the scribe usage.

**Comment by darkfrog26** [comment]
Can you clarify how it doesn't work as expected?

**Comment by david-bouyssie** [comment]
I was expecting that changing the Handler minimumLevel to a specific value would eliminate logging for inferior levels.

**Comment by darkfrog26** [comment]
It should. Are you adding an additional handler later perhaps?

**Comment by david-bouyssie** [comment]
I'm changing the scribe configuration at a single place and these are the only changes I'm doing.
Moreover isolated the code in a single test to be sure there was not interference with something else.
I can pastebin this test if you want.

**Comment by darkfrog26** [comment]
Ah, sorry for not noticing this sooner, but the problem is that you're not calling `.replace()` at the end, so that block doesn't actually do anything. ;)

**Comment by darkfrog26** [comment]
```scala
object Test {
  def main(args: Array[String]): Unit = {
    Logger.root.clearHandlers().clearModifiers().withHandler(minimumLevel = Some(Level.Info)).replace()
    scribe.trace("Trace")
    scribe.debug("Debug")
    scribe.info("Info")
    scribe.error("Error")
  }
}
```

Works exactly as expected.

**Comment by darkfrog26** [comment]
Scribe follows a builder pattern, but with immutability, allowing you to derive new loggers from existing one or modify one, but for the latter, you have to call `replace()` or it isn't clear what you want to do with your new logger.

**Comment by david-bouyssie** [comment]
Oh yes, sorry my mistake... 🤦‍♂ 

BTW, is there a simple way to disable logging from the root?
It seems that putting None in minimumLevel allows all levels.
This was the purpose of my second filter (when scribeMinLogLevelOpt is empty).

**Comment by darkfrog26** [comment]
You already `clearHandlers()` just don't add any...

**Comment by david-bouyssie** [comment]
Ok thank you for the tip.

Then here is my final solution:

```scala
val logger = scribe.Logger.root.clearHandlers().clearModifiers()
if (scribeMinLogLevelOpt.isDefined) {
  logger.withHandler(minimumLevel = scribeMinLogLevelOpt).replace()
} else {
  logger.replace()
}
```
