### ISSUE TITLE
Make SLF4J requested loggers have parentage rules similar to log4j2 or logback.

### ISSUE THREAD

**Issue by markehammons** [outr/scribe#124]
Right now, loggers instantiated by things using slf4j are hard to deal with. There's no automated way to parent them, so special rules (for example, to enable debug or trace on a certain library) requires setting root to trace or debug, and then overriding the specific loggers you want to clean up your logs.

It would be nice instead that if you define a logger "com", then slf4j created loggers with names like "com.A" will use it as a parent automatically.

**Comment by darkfrog26** [comment]
You technically can, though it's not as straight-forward as would be ideal. You can define the structure yourself:
```scala
Logger("com").replace()
Logger("com.A").withParent("com").replace()
Logger("com.A.B").withParent("com.A").replace()
```

I'd need to think about this more to see if this could be automated, but frankly, using SLF4J is a limiting factor on your project, so where possible, you should really migrate to using Scribe directly.

**Comment by markehammons** [comment]
I’m using something like the above for the classes in my codebase. The problem comes from trying to control logging events from slf4j using stuff outside the codebase. 

If there’s some sort of automated parent-child relationship that’s finer grained than root for classes that are getting loggers from scribe through the slf4j adapter, that would help control logging on these classes much better.

**Comment by darkfrog26** [comment]
Can you offer up some pseudo-code of how you envision this would work best for your use-case?

**Comment by markehammons** [comment]
What my goal is is to be able to do

```scala
Logger("com").withMinLevel(Info).replace()
```

and then if some slf4j thing comes looking for `Logger("com.sun.Unsafe")` then it'd have the above `Logger("com")` as its parent instead of root. I have some ideas of how to do this (like for example a trie like lookup to find the closest defined parent logger), but I haven't got a working prototype on my current code yet.

In any case, my thought is that this would be a special case for slf4j, to ease controlling things logging via it so you're not stuck with either controlling them via the root logger, or controlling them directly.

**Comment by darkfrog26** [comment]
That seems reasonable.

**Comment by darkfrog26** [comment]
Would you be up to testing a snapshot locally? I'll work up something and I think I'm going to make this a core feature so that you can define hierarchical parentage in normal operation as well.

**Comment by markehammons** [comment]
Sure, that'd be fine!

**Comment by markehammons** [comment]
Thinking on this tonight, I thought of an alternative implementation that wouldn't require an additional datastructure.

Say you have `com.sun.Unsafe`. You try to fetch the logger, and if it's not already allocated you create one with that name. Then, you search in reverse to try to find parents. You search for the `com.sun` logger, then the `com` logger, and finally fall back to the root logger.

I believe this could be done pretty efficiently using java's string utils to get the indices of the `.` characters in the name, and then cutting the string into smaller and smaller chunks.

In the end, I think the Logger would look like `Logger("com.sun.Unsafe").withParent(Option(Logger("com.sun")).orElse(Logger("com")).getOrElse(Logger.root)))`. For scala objects using the scribe logger directly and not slf4j, you could probably also use a macro to generate that chain at compile time instead of parsing the class name at runtime.

**Comment by darkfrog26** [comment]
Take a look at the latest code in master (`2.8.0-SNAPSHOT`). It's actually fairly similar to what you laid out here. It bodes well that we had a similar idea. :)

**Comment by darkfrog26** [comment]
When you call `Logger("com.sun.Unsafe")` if the logger doesn't already exist, before creation, it detects dot-separation and calls `Logger("com.sun")` to get the parent that will automatically be assigned to it, and it, in turn, creates `Logger("com")` for its parent. The beauty of this model is that if they already exist, they are used, and in future calls to the same package, no additional cost is incurred.

**Comment by darkfrog26** [comment]
Check this out, `publishLocal`, and let me know if this solves your problems and I'll get a new release out tomorrow.

**Comment by markehammons** [comment]
@darkfrog26 I'll try to test this this weekend. There's still a lot of work to be done if I want to know if I can add scribe to my project, and I have to sell my superiors on switching away from logback (something I think is doable, but still is seperate from my current work).

**Comment by darkfrog26** [comment]
Sounds good. I'll hold off on releasing 2.8 until I hear back from you, but this is the last remaining issue on my agenda. Let me know if there's anything else that would make it easier to sell. I know how much of a pain it can be to get buy-in for stuff like this. I'm actually in the process of bringing it into my new employer myself (eBay).

**Comment by markehammons** [comment]
So I've tested it and the parentage works. However, you may want to address this new issue in some way before releasing 2.8.

#127

**Comment by darkfrog26** [comment]
2.8.0 is now released
