### ISSUE TITLE
Logging levels are unintuitive

### ISSUE THREAD

**Issue by markehammons** [outr/scribe#127]
When writing a parent and child logger, I would expect to be able to use the .withMinimumLevel to control the logging levels of a logger appropriately. As an example:

```scala
    scribe.Logger.root.withMinimumLevel(Level.Error).replace()
    scribe.Logger("com").withMinimumLevel(Level.Info).replace()
```

This seems like it would be the appropriate code to make the root logger (and children) log error level messages, and to make the com logger ignore that and log info level messages.

It does in fact make the root logger only log Error level messages. However, it also makes the com logger only log error level messages despite its minimumLevel being set to info.

In reality, to control logging levels appropriately, I must do:
```scala
    scribe.Logger.root.clearHandlers().withHandler(minimumLevel = Some(Level.Error)).replace()
    scribe
      .Logger("com")
      .clearHandlers()
      .withHandler(minimumLevel = Some(Level.Info))
      .replace()
```

There are a couple of issues with this. Having levels controlled at the handler level makes it necessary to reconfigure handlers defined at the root level, so instead of saying "I want the FileWriter and ConsoleLogger to log all messages at the root level", I now have to say at every level what handlers I want handling log events if I want to change log level.

**Comment by markehammons** [comment]
Having seperate handlers is also a bit dangerous because if root is not filtering com's logging events, the two seperate handlers will both print com's logging messages, resulting in doubled logs.

**Comment by darkfrog26** [comment]
This is a great point.

**Comment by darkfrog26** [comment]
Okay, this is resolved and will go in 2.8. See: https://github.com/outr/scribe/blob/master/core/shared/src/test/scala/specs/LoggingSpec.scala#L293

**Comment by markehammons** [comment]
I've tested this on my branch and it works very well. With the addition of a few more features on our side, I believe this will be an excellent replacement for logback/log4j2 for us.

**Comment by darkfrog26** [comment]
@markehammons glad to hear it. Please keep in touch and let me know if there's anything else that would make Scribe a more useful library for you.

**Comment by darkfrog26** [comment]
2.8 will be released today or tomorrow most likely.

**Comment by markehammons** [comment]
@darkfrog26 
did you build 2.8 with a jvm > 8? I cannot seem to use the binaries with a java 8 jdk

**Comment by darkfrog26** [comment]
That's not good. Let me check and I'll get back to you.

**Comment by darkfrog26** [comment]
Okay, I just pushed `2.8.1` with Oracle Java 8. Please let me know if you have any trouble with it.

**Comment by markehammons** [comment]
I'll give it a shot tomorrow.

**Comment by SethTisue** [comment]
> I cannot seem to use the binaries with a java 8 jdk

What is the error message?

**Comment by markehammons** [comment]
@SethTisue I don't have the exact error cause I'm working on a different branch at the moment, but it was something about the slf4j.impl classes' bytecode being a newer version than my jvm's. I usually get that error if I compile the binaries with jdk11 and try to run with jdk8

**Comment by darkfrog26** [comment]
Oops. I was mistaken. I forgot that the SLF4J integration uses a Java source file because of MDC's singleton reference.

Sorry @SethTisue, you called it.

@markehammons, well, this shouldn't be a problem in `2.8.1`
