### ISSUE TITLE
Scala 3 Support

### ISSUE THREAD

**Issue by darkfrog26** [outr/scribe#128]
This one is complicated as the macros all need to be completely re-written

**Comment by Miuler** [comment]
what happened whith support for scala 3?

**Comment by darkfrog26** [comment]
@Miuler we have Scala 3 support (at least 0.27.0-RC1) and as soon as utest gets their build fixed for 3.0.0-M1 (hopefully this week), then it will allow me to release Scribe 3.2 with 3.0.0-M1 support. The dependency chain is: utest -> geny -> upickle -> profig -> scribe.
