### ISSUE TITLE
Ansi color support

### ISSUE THREAD

**Issue by KyleU** [outr/scribe#13]
Helper methods to decorate loggers with terminal colors. Currently works with `logger.string("\e...")`, but it's a hassle.

https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

**Comment by darkfrog26** [comment]
That's a good idea.  Would you be interested in writing them? :)

**Comment by darkfrog26** [comment]
Have you considered just using http://www.scala-lang.org/api/2.12.x/scala/io/AnsiColor$.html ?

**Comment by KyleU** [comment]
Wow, that would have saved me an hour... Easy enough, thanks for the find!

**Comment by darkfrog26** [comment]
No worries. Glad I could help. :)
