### ISSUE TITLE
JSON Logging Support

### ISSUE THREAD

**Issue by darkfrog26** [outr/scribe#137]
The ability to log to JSON records would provide substantial benefit to anyone that wants to parse the logs later

**Comment by therockstorm** [comment]
It seems the [`scala-logging`](https://github.com/lightbend/scala-logging) repo is no longer maintained so we're looking to move to one that supports Scala 3 macros. We log to JSON to make ingestion into DataDog simpler. This library looks great, but we'd need this.

**Comment by darkfrog26** [comment]
This is on the agenda to add in the near future, but Circe support for Dotty is not really there, so I've been holding off.  If you don't need Dotty support you could take a look at what `scribe-logstash` does and replicate that?

**Comment by darkfrog26** [comment]
Preliminary support has been added and will go out in version `3.2`. If you want anything more advanced, please create another ticket to outline your needs.
