### ISSUE TITLE
Default output doesn't show in dark terminal.

### ISSUE THREAD

**Issue by ckipp01** [outr/scribe#142]
Using a very basic project, if you are using a dark terminal background, the out output is also in a very dark color making it impossible or very difficult to see. I'll paste three examples below with three different themes. They are all just including `3.1.2` of scribe and doing a simple `scribe.info`.

<img width="1226" alt="Screenshot 2020-11-27 at 11 18 35" src="https://user-images.githubusercontent.com/13974112/100438413-67d85c80-30a2-11eb-9377-7e3f39fac438.png">
<img width="1209" alt="Screenshot 2020-11-27 at 11 18 55" src="https://user-images.githubusercontent.com/13974112/100438417-6870f300-30a2-11eb-9b45-247cea1f7fb4.png">
<img width="994" alt="Screenshot 2020-11-27 at 11 19 13" src="https://user-images.githubusercontent.com/13974112/100438420-69098980-30a2-11eb-9595-a99e45fa3941.png">

So as you can see, starting with the darkest, the text is impossible to see. As I go to a more medium color, the text is there, but very faint. It's not until you're in a light themed terminal that the output is clear.

Would it be possible to change this default behavior to ensure that whichever background your terminal is the output would be clear and visible?

**Comment by darkfrog26** [comment]
I've seen this when running in certain dark modes in terminals. I'll see what I can do about changing the default before the next release. However, in the short-term you can copy-and-paste the existing `Formatter` and change the colors for your specific needs if desired.
