### ISSUE TITLE
Add way to bring own scribe mdc implementation

### ISSUE THREAD

**Issue by jvican** [outr/scribe#143]
Hi 👋 I've currently inlined some of the sources to integrate with slf4j because I need to create my own implementation of `ScribeMDCAdapter` to use another mechanism than thread locals to propagate values across the log call sites (more concretely, a version that supports Monix locals).
  
Would it be possible to make the mdc adapter configurable, maybe via a service loader? It would help me remove the 5 source files I had to copy to get Monix locals working.

**Comment by jvican** [comment]
@darkfrog26 Another ask: would it be possible to remove the inlined use of the global scheduler pool in https://github.com/outr/scribe/blob/master/core/jvm/src/main/scala/scribe/Platform.scala#L17? Seems a bit overkill for the purpose. I think something like that could be achieved with service loaders in a more robust way and without initializing the global scala thread pool, which might not be used by the user.

**Comment by darkfrog26** [comment]
@jvican I don't see any problem with either of those, but would you be interested in putting together a couple of PRs to introduce the changes?

**Comment by jvican** [comment]
I might, but over the next months as I don't have a lot of free time now. It's not urgent. In the meanwhile I'll continue using the old version I'm using.

**Comment by darkfrog26** [comment]
If I find the time to tackle this before you do I'll reply to this ticket and let you know.

**Comment by darkfrog26** [comment]
This will be released with 3.3.0
