### ISSUE TITLE
Async tracing wiki out of date

### ISSUE THREAD

**Issue by tanzoniteblack** [outr/scribe#148]
Release [3.0.0](https://github.com/outr/scribe/releases/tag/3.0.0) states that the async/future code was removed, but the [wiki](https://github.com/outr/scribe/wiki/asynchronous-tracing) & readme still contains documentation around it.

**Comment by darkfrog26** [comment]
Good catch. Adding this to 3.2 to make sure it gets done as other docs need to be revised for that release.
