### ISSUE TITLE
Add description how to change log level on the fly to Wiki

### ISSUE THREAD

**Issue by sergeda** [outr/scribe#149]
There is a feature "Hot-change capabilities to modify how logging works in real-time" in the feature's list. But I was not able to find details how to use that feature in the docs. Please, add it.

**Comment by darkfrog26** [comment]
I'll be updating the wiki quite a bit before the release of 3.2, so I'll add this to the agenda.

If you want to tell me how you have logging configured currently, I can quickly explain how to change it live.

**Comment by darkfrog26** [comment]
Updated the features list to offer a very simple example (https://github.com/outr/scribe/wiki/Features)

I'll try to update the getting started tutorial in the near future to break out feature-by-feature functionality.
