### ISSUE TITLE
Set log level globally

### ISSUE THREAD

**Issue by Tamriel** [outr/scribe#15]
`Logger.root.addHandler(LogHandler(level = Level.Error))` does not show an effect

**Comment by darkfrog26** [comment]
The effect would be a duplicate logging of errors to the console.  What are you trying to accomplish?

**Comment by Tamriel** [comment]
I want to change the global log level.

**Comment by darkfrog26** [comment]
Try:

```scala
Logger.root.clearHandlers()
Logger.root.addHandler(LogHandler(level = Level.Error))
```

**Comment by darkfrog26** [comment]
@Tamriel Can you close this if it fixed your problem?
