### ISSUE TITLE
Config how the log looks like

### ISSUE THREAD

**Issue by Tamriel** [outr/scribe#16]
e.g. don't show the date

**Comment by darkfrog26** [comment]
You can configure this via `Formatter` when adding a `LogHandler`.  `Formatter` companion has three pre-defined scenarios (`simple`, `default`, and `trace`).  Building your own `Formatter` instance is quite easy with `FormatterBuilder`:

`FormatterBuilder()..string("[").threadName.string("] ").levelPaddedRight(" ").positionAbbreviated.string(" - ").message.newLine` would identical to default formatting, but without the date stamp.

**Comment by Tamriel** [comment]
Great :-)
It would be nice to have this in the README file.

**Comment by darkfrog26** [comment]
I'm slammed at the moment, would you mind adding a PR?
