### ISSUE TITLE
Support for execution inside spark/flink

### ISSUE THREAD

**Issue by Eli-Golin** [outr/scribe#202]
Are there any plans to release a spark or flink supporting version (mainly serialization issues)?

**Comment by darkfrog26** [comment]
Scribe actually works great with Spark if you set it up properly. If you have specific issues please let me know and I'll try to address them, but you just have to make sure your initialization of Scribe configuration occurs within the scope of the Spark jobs and everything just works. I know that Scribe is being heavily used at eBay within Spark jobs with no issues.

**Comment by Eli-Golin** [comment]
Tnx.. I believe it was my mistake.
Great library , great work!!

**Comment by darkfrog26** [comment]
Thanks. Reach out here or on Gitter if you run into any other issues.
