### ISSUE TITLE
Asynchronous logging for JVM

### ISSUE THREAD

**Issue by shawjef3** [outr/scribe#21]
My understanding is that Javascript is always single threaded, so I am unsure if this only applies to the JVM implementation or not.

Logging frameworks such as Log4j use asynchronous logging. This has the benefits of

- exceptions while logging happen in another thread, not your own
- CPU time used for logging does not delay your thread (if a hardware thread is available)

I have a benchmark showing Scribe's overhead vs. log4j 2.10. Note that this measures the thread-local CPU time used when calling log methods, and is not intended to show anything else. Because log4j is asynchronous, I expect its logging calls to return more quickly.

```
[info] Benchmark                            Mode  Cnt   Score    Error  Units
[info] LocalThreadOverhead.baseLine         avgt    5   0.004 ±  0.001  ns/op
[info] LocalThreadOverhead.withJavaLogging  avgt    5  20.766 ±  0.635  ns/op
[info] LocalThreadOverhead.withLog4j        avgt    5   1.746 ±  0.019  ns/op
[info] LocalThreadOverhead.withScribe       avgt    5  47.656 ±  6.855  ns/op
```

See https://github.com/shawjef3/scribe/blob/benchmarks/benchmarks/src/main/scala/scribe/benchmarks/LocalThreadOverhead.scala for the implementation.

**Comment by shawjef3** [comment]
Some relevant reading: https://logging.apache.org/log4j/2.x/manual/async.html

**Comment by darkfrog26** [comment]
You should really add a validation mechanism to confirm that the logging actually completes.  Otherwise, it's not a fair benchmark.  For example, log4j can say it cranked through 1,000 log events, but it may have only completed a handful if it's running asynchronously.  I know this is probably your point, but it would be a worthwhile data point to show time to actual completion in contrast to the asynchronous "complete".

**Comment by darkfrog26** [comment]
I'm not opposed to adding support for this.  In fact, in an earlier iteration, I did have support, but it was causing some problems with records not being guaranteed to be written before the application terminated.  As a result, I opted to make everything synchronous as the performance was still incredibly good.

**Comment by darkfrog26** [comment]
If you'd like to discuss more directly, please join the Gitter channel: https://gitter.im/outr/scribe

**Comment by shawjef3** [comment]
I think the trick to making sure all messages make it out on shutdown is to use `Runtime#addShutdownHook`.

**Comment by darkfrog26** [comment]
We can do that, but it's not reliably invoked so there will always be the risk of some logs not being written.

**Comment by darkfrog26** [comment]
I don't have a problem with this as long as synchronous is default operation.

**Comment by shawjef3** [comment]
Please take a look at https://github.com/shawjef3/scribe/blob/asynchronous/jvm/src/main/scala/scribe/Main.scala. I think you will be pleased with how it behaves. I added a `flush()` method in case you wanted to really be careful.

**Comment by shawjef3** [comment]
```
[info] Benchmark                            Mode  Cnt   Score    Error  Units
[info] LocalThreadOverhead.baseLine         avgt    5   0.002 ±  0.001  ns/op
[info] LocalThreadOverhead.withAsyncScribe  avgt    5  12.097 ±  2.316  ns/op
[info] LocalThreadOverhead.withLog4j        avgt    5   1.590 ±  0.182  ns/op
[info] LocalThreadOverhead.withScribe       avgt    5  40.791 ±  3.065  ns/op
```

**Comment by darkfrog26** [comment]
@shawjef3 I could be convinced of this route, but if I'm going to be convinced, we at least have to be able to out-perform log4j. :-p

**Comment by shawjef3** [comment]
Log4j is very well optimized. Maybe you are thinking of Log4j version 1? See https://logging.apache.org/log4j/2.x/performance.html

**Comment by darkfrog26** [comment]
I can't have Scribe running slower.  I think I'll have to spend a bit of time performance tuning.  You're welcome to submit a PR for this, but I imagine I'll be doing a fairly large re-write in the not too distant future.

**Comment by darkfrog26** [comment]
I've been working on this with regard to Scribe 2.0 which is almost ready to be released:

```
[info] Benchmark                              Mode  Cnt     Score       Error  Units
[info] LoggingSpeedBenchmark.baseLine         avgt    3     0.002 ±     0.008  ns/op
[info] LoggingSpeedBenchmark.withLog4j        avgt    3  7629.518 ± 15058.806  ns/op
[info] LoggingSpeedBenchmark.withScribe       avgt    3  2804.288 ± 12305.478  ns/op
[info] LoggingSpeedBenchmark.withScribeAsync  avgt    3   869.001 ±   755.981  ns/op
```

BTW, I built the system based on your original benchmarks, but the reason that log4j in your benchmark was so fast was because it was immediately escaping after a "should log" for "info" returns false.  After adding proper configuration I'm doing file logging in the three benchmarks and I'm kicking log4j's butt!
