### ISSUE TITLE
Scala Native performance issue (silent logs)

### ISSUE THREAD

**Issue by david-bouyssie** [outr/scribe#220]
I'm testing Scribe using the latest version of Scala Native (current master), but I think the problem is the same with the latest release.

The issue I observed is a whole program slowdown when using `logger.trace`  and with a `minimumLevel` that is higher than trace, meaning that trace messages should be ignored.

To reproduce I think just a simple while loop (with 10M iterations) is enough:
```
val MAX_ITER = 10000000
var i = 0
while (i < MAX_ITER) {
  logger.trace("my simple message")
  i += 1
}
```

On my laptop this loop takes more than 39s to finish on `release-fast` mode.

However protecting the `logger.trace` with an `if` statement helps of course to retrieve the normal while loop duration, which runs almost instantaneously:
```
val MAX_ITER = 10000000
var i = 0
val isTraceEnabled = false
while (i < MAX_ITER) {
  if (isTraceEnabled) logger.trace("my simple message")
  i += 1
}
```

**Comment by darkfrog26** [comment]
What about if you replace `isTraceEnabled` with `logger.includes(Level.Trace)`?

**Comment by david-bouyssie** [comment]
`logger.includes(Level.Trace)` behaves the same as the first example

However adding `if (logger.includes(Level.Trace)) System.exit(1)` exits the program, which means that it returns true.

**Comment by darkfrog26** [comment]
If you're willing, could you check out `3.6` branch and `publishLocal` to see if that solves your problems? Still a work-in-progress, but it makes some sweeping changes and bug fixes related to this.

**Comment by darkfrog26** [comment]
With the following code, I was able to reproduce a major performance hit on ScalaNative:
```scala
import scribe.data.MDC
import scribe.handler.LogHandler
import scribe.{LogRecord, Logger}

import java.util.concurrent.atomic.AtomicLong

object Test {
  def main(args: Array[String]): Unit = {
    val counter = new AtomicLong(0L)

    Logger.root.clearHandlers().clearModifiers().withHandler(new LogHandler {
      override def log[M](record: LogRecord[M]): Unit = counter.addAndGet(MDC.get("value").get.asInstanceOf[Long])
    }).replace()

    val start = System.currentTimeMillis()
    val Iterations = 10000000L
    (0L until Iterations).foreach { i =>
      MDC.contextualize("value", i) {
        scribe.trace("my simple message")
      }
    }
    println(s"Counter: ${counter.get()} in ${(System.currentTimeMillis() - start) / 1000.0} seconds")
  }
}
```

On my laptop, JVM takes 2 seconds to complete and on Native, it takes 20 seconds.
