### ISSUE TITLE
sl4j support doesn't work with Java 11

### ISSUE THREAD

**Issue by sarahjryan** [outr/scribe#243]
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/.../AppData/Local/Coursier/cache/v1/https/.../artifactory/maven2-repo/com/outr/scribe-slf4j_2.13/3.6.3/scribe-slf4j_2.13-3.6.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]

http://www.slf4j.org/codes.html#ignoredBindings

Any chance of an update to 1.8?

**Comment by darkfrog26** [comment]
Absolutely. I'll take a look at this today.

**Comment by darkfrog26** [comment]
@sarahjryan, to be clear, you want me to update to `1.8.0-beta4`?

**Comment by darkfrog26** [comment]
Have you considered just switching to `scribe-slf4j2` that uses the 2.0 alpha?

**Comment by darkfrog26** [comment]
version `1.7.32` appears to be the latest release version.

**Comment by darkfrog26** [comment]
New release `3.6.4` is out now and you can use `scribe-slf4j2` that relies on slf4j `2.0.0-alpha5`. That should solve your problems. After doing more research, I don't want to switch to the 1.8 beta because it doesn't seem to be maintained and 2.0 appears to be the eventual goal.
