### ISSUE TITLE
SystemOutputLogger: option to always log to one stream

### ISSUE THREAD

**Issue by eikek** [outr/scribe#272]
Hi,

Thank you for sharing scribe!

I was wondering what you think about providing an option for `SystemOutputLogger` to always log to either stdout or stderr, not looking at the log level? For my application I would prefer to always use stdout. Currently I need to copy the code into my codebase, not a big deal, but would be more convenient if there was a setting or some other means to reuse the "write" implementation.

**Comment by darkfrog26** [comment]
I wouldn't mind extracting the functionality to a more general-purpose method. Can you shed some light on your use-case to make sure it fits your needs?  Why not just call `SystemOutputLogger.write(...)` from your code?

**Comment by eikek** [comment]
Calling `SystemOutputLogger.write(…)` would be just fine! Not sure if I missed something. I think it currently chooses either stderr or stdout based on the log level.  
```scala
  val stream = if (record.level <= Level.Info) {
    Logger.system.out
  } else {
    Logger.system.err
  }
```
I would like to always log to stdout (or stderr), including levels higher than Info. i don't know how to control this from outside.

**Comment by darkfrog26** [comment]
@eikek, can you take a look at the commit I just pushed and verify that solves your problem appropriately?

**Comment by eikek** [comment]
Hi @darkfrog26 oh thank you very much! This works very nicely. I can then just say `logger.withHandler(writer = SystemOutWriter)` in my config. 👍🏼

**Comment by darkfrog26** [comment]
Good deal. I'll try to get a new release out ASAP.

**Comment by darkfrog26** [comment]
@eikek, `3.8.0` is now released with these changes

**Comment by eikek** [comment]
Thank you very much!
