### ISSUE TITLE
Add logical operators on `Filter`

### ISSUE THREAD

**Issue by Fristi** [outr/scribe#273]
Do you think this makes sense?

```scala
def &&(other: Filter): Filter = new Filter {
  def matches[M](record: LogRecord[M]): Boolean = filter.matches(record) && other.matches(record)
}
```

```
.withModifier(exclude(packageName.startsWith("org.http4s.blaze") && level < Level.Warn))
```

**Comment by darkfrog26** [comment]
@Fristi, yes, that's a great idea. I went ahead and created a new commit to add this functionality. Take a look and let me know if there's anything I missed. Thanks for the great idea!

**Comment by Fristi** [comment]
Great thanks! Maybe `||` as well ?

**Comment by darkfrog26** [comment]
You went and had to make it more complicated, didn't you? :)  I added `||` support. Let me know if you think of something else.

**Comment by Fristi** [comment]
Looks great! Thanks for the quick add

Works superb with Slf4j and GraalVM

**Comment by darkfrog26** [comment]
@Fristi, great to hear! Please feel free to make any additional suggestions or offer feedback as you continue to use Scribe. I'm always happy to hear feedback that helps make it better.
