### ISSUE TITLE
conflict with profig

### ISSUE THREAD

**Issue by ahuret** [outr/scribe#294]
Hello, thank you for this nice library ! :-)

We've been using profig and scribe for two years for configuration and logging management.
Since we've updated new versions of both, we found an unexpected issue, that's looks like a conflict between the libraries.
When I create a `scribe.Logger`, then load a yaml file using profig, there is a Runtime Exception:

`Caused by: java.lang.AbstractMethodError: Receiver class profig.ProfigYaml$ does not define or inherit an implementation of the resolved method 'abstract fabric.Value apply(java.lang.String)' of interface profig.ProfigJson.` .

Here is a MRE that hit the issue:

```scala
import profig._
import scribe.handler.LogHandler

object Main extends App {
 var logger = scribe.Logger.empty.withHandler(LogHandler())
  Profig.loadFile(file = new java.io.File("/config.yaml"), errorHandler = Some(((e: Throwable) => e.asInstanceOf[RuntimeException].printStackTrace)))
}
```

I bet there is some global variable(s) shared between the libraries that could be the cause.

Thank you in advance !

**Comment by ahuret** [comment]
It appears that with json and xml config it works well, issue is only with yaml format

**Comment by darkfrog26** [comment]
It looks like a version difference. Are you sure you're using the latest version of Profig, Fabric, and Scribe?

**Comment by ahuret** [comment]
looks like issue is when profig-yaml is imported, here the versions:

"com.outr" %% "scribe" % "3.8.0"
"com.outr" %% "profig" % "3.2.9"
"com.outr" %% "profig-yaml" % "3.1.2"

by the way, looks like we can load yaml file without `profig-yaml` in build.sbt, so when use `profig-yaml` ?

**Comment by darkfrog26** [comment]
Ah, that's because `profig-yaml` is deprecated. It was replaced with `fabric-parse` when `profig` switched to using https://github.com/outr/fabric. It might just magically work if you remove the `profig-yaml` dependency.

**Comment by ahuret** [comment]
Ok, thank you :+1: Closing it
