### ISSUE TITLE
Support outputting logstash formated logs to stdout

### ISSUE THREAD

**Issue by keirlawson** [outr/scribe#301]
We have a datadog setup that ingests logs that we produce to standard out, so it would be great to have a way to output logstash encoded logs there rather than forwarding them over the network directly as the current logstash module appears to work.

**Comment by darkfrog26** [comment]
@keirlawson I'd be happy to support that. Would you be interested in creating a PR to represent exactly what you need so you can verify it fits properly? If you're not up for it I can try to get to it in the next few days.

**Comment by keirlawson** [comment]
I guess ideally just having a `Formatter` that produced the JSON output would do the trick, if it could be possible to get such a thing whilst avoiding the `youi-client` dependency that would be a bonus, but I appreciate that may not be the best way to structure the project.

**Comment by darkfrog26** [comment]
Why not use `scribe-json`?

**Comment by keirlawson** [comment]
I hadn't actually spotted that module, will give it a go :)

**Comment by keirlawson** [comment]
So far as I can see it is not possible to customise the outputted JSON fields with that module? I ask because per https://docs.datadoghq.com/logs/log_configuration/attributes_naming_convention/ DataDog seems to expect a `message` field, whereas the JSON module produces instead a `messages` array which I don't think will be picked up correctly by DD... maybe we could add a custom formatter specifically for DataDog?

**Comment by darkfrog26** [comment]
@keirlawson I'm currently re-working `scribe-json` to default to a format that DataDog can handle and adding more flexibility to make customization easier, but for your needs, is this good:
```json
{
  "methodName": "JsonWriterSpec",
  "data": {
  },
  "traces": [
  ],
  "date": "2021-01-01",
  "className": "spec.JsonWriterSpec",
  "time": "03:00:00.000-05300",
  "level": "INFO",
  "line": 25,
  "levelValue": 300.0,
  "fileName": "JsonWriterSpec.scala",
  "timeStamp": 1609488000000,
  "message": "Hello, Json!",
  "column": null
}
```
Are there are any other changes that need to be made to properly support DD?

**Comment by darkfrog26** [comment]
The `message` field auto-flattens to the single value if there's only one message and expands to an array if there are multiple.

**Comment by darkfrog26** [comment]
I created a PR to represent these changes: https://github.com/outr/scribe/pull/302

**Comment by keirlawson** [comment]
I've confirmed that the JSON module now works with Datadog out of the box

I did notice though that in swapping our logback for scribe various custom tags that we add via log4cats `addContext` are no longer present on the logs.  Should I open a separate bug for this?

**Comment by darkfrog26** [comment]
@keirlawson, yes, please do. If you can give any examples I can reproduce in test it will help me make sure I address the issue.

**Comment by darkfrog26** [comment]
closing this issue and it will go with the next release, but I'll hold off on releasing until we can address the `addContext` as well.
