### ISSUE TITLE
scribe-json ignores slf4j MDC values when outputting

### ISSUE THREAD

**Issue by keirlawson** [outr/scribe#304]
In order to pass along metadata to the underlying logger, libraries such as log4cats use slf4j's MDC.  Unlike for example logback's logstash encoder scribe-json does not appear to output MDC values associated with loggers, per the example below:

```scala
import scribe.Level
import scribe.json.JsonWriter
import scribe.writer.SystemOutWriter
import org.slf4j.LoggerFactory
import org.slf4j.MDC

scribe.Logger.root
    .clearHandlers()
    .clearModifiers()
    .withHandler(
      minimumLevel = Some(Level.Debug),
      writer = new JsonWriter(SystemOutWriter)
    )
    .replace()

val logger = LoggerFactory.getLogger("test-logger")
MDC.put("key", "value")
logger.info("this is a test")
```

Gives the following, with no mention of the key/value metadata

```
{"methodName":null,"trace":null,"data":{},"date":"2022-06-24","className":"test-logger","time":"21:58:55.661+-1-60","level":"INFO","line":null,"levelValue":300.0,"fileName":"","timeStamp":1656104335661,"message":"this is a test","column":null}
```

**Comment by darkfrog26** [comment]
@keirlawson thanks for the heads up on this. For some reason, I just completely forgot about MDC when implementing the output.  The fix should go with the next release.
