### ISSUE TITLE
Easier Support to Update Logger

### ISSUE THREAD

**Issue by darkfrog26** [outr/scribe#31]
Updating the root logger requires something like: `Logger.update(Logger.rootName)(_...)` which should be able to simplified greatly.  In addition, the `updateLogger` method is problematic.

**Comment by ml10** [comment]
I'm having trouble getting the exact configuration I'm looking for. I created [a scastie](https://scastie.scala-lang.org/Ditdb8qDTbeRtFgvAyhO4g) demonstrating the issue.

I would expect that both methods of configuration would result in the same logging, but grabbing the logger and running each method separately seems to have a different outcome than chaining the `clearHandlers` and `withHandler`. I expected to see line 10 emitted.

Additionally, the chained configuration seems to result in the `INFO` message getting emitted twice. My hunch with this configuration was that line 12 would have been emitted once.

What is the recommended way to change the minimum log level, but not duplicate messages emitted from higher log levels?

Thank you for scribe! A logging library with configuration through code and without a hard requirement on other logging frameworks is very compelling!

**Comment by ml10** [comment]
Ah, I see my misconception with the separated calls. They return the updated `Logger` which would then need to be updated.

With that misconception out of the way, here's [a simpler scastie](https://scastie.scala-lang.org/0Em9NEwWTC2MalaIObWLug) showing the `INFO` messages being emitted twice.

**Comment by darkfrog26** [comment]
The problem is that you're adding a second `ConsoleWriter` by using `withHandler`.  There is one assigned to `root` by default and you're adding one to your class-level as well.  You have a couple options:

1.) Work with the root logger: `Logger.update(Logger.rootName)(_.clearHandlers().clearModifiers().withHandler(minimumLevel = Level.Debug))` - Notice you have to clear handlers and modifiers (since modifiers is defining a minimum level to Info by default)
2.) Orphan your logger so it doesn't propagate up to the root: `Logger.update("org.ml10.ScribeDoubleInfo")(_.orphan().withHandler(minimumLevel = Level.Debug))`

This is more complicated than it should be though.  I need to spend some more time trying to make thise both easier to code as well as easier to reason about.

**Comment by darkfrog26** [comment]
@ml10, is it working for you now?

**Comment by ml10** [comment]
Yeah, the `orphan` approach works. In the app, I'd rather not change the minimumLevel for the root logger, only for targeted classes.

Just to validate my understanding of how `orphan` works: When a new logger is created, it takes it's definition from it's parent logger (root by default) and then if it is ophaned, and further changes are made to the parent logger, the orphan child logger will not reflect those changes, right?  Meaning they lose the relationship, but the orphan still starts with a base config inherited from what was it's parent at the time. Once it's orphaned it's not starting completely from scratch configuration-wise, right?

So would a recommended configuration approach for the current state of scribe be something like the following?

1. Configure root logger with "base" configuration to be shared among all loggers.
1. Create children loggers from root logger
1. for each child logger, orphan it and apply custom configuration

**Comment by darkfrog26** [comment]
No, it's not so complicated as that. This is a simple parent-child relationship with propagation.

When a new logger is created it defines (by default) its parent as the root logger.  Any log events that occur on that logger propagate up to its parent logger.  When you `orphan()` a Logger you are setting its parent to `None` so that it no longer propagates up any higher when logging occurs on it.  This means that log events fire on that logger, but not on the root logger.

This is also why when you add a handler (even after clearing all handlers on your explicit logger) it logs twice because there's a default console logging handler on the root logger.

**Comment by darkfrog26** [comment]
@ml10 and @asakaev, I'd be interested in some feedback about how you'd like to see this?  I'm having trouble coming up with an ideal solution that maintains a clean interface while maximizing flexibility.

**Comment by darkfrog26** [comment]
I've added a new feature to `Logger` to represent a unique `id`.  This allows an immutable `Logger` to be copied while keeping the original `id` which can then be used to replace previous copies via name reference.

So, instead of:

```scala
Logger.update("loggerName")(_.orphan().withHandler(...))
```

You can write:

```scala
logger.orphan().withHandler(...).replace()
```

The new `replace` method will handle all of the complexity of finding all logger instances this should replace.
