### ISSUE TITLE
Log4JMigrationjava NoSuchElementException: Add a default value for EventCounter 

### ISSUE THREAD

**Issue by aiminguo** [outr/scribe#374]
Got this NoSuchElementException, please Add a default value for EventCounter and silent this exception. 

The log did work as expected except this initialization exception.

2022.12.19 14:00:33:360 [Driver] ERROR scribe.Log4JMigration.error:25 - Error loading Log4JMigrationjava.util.NoSuchElementException: key not found: EventCounter
	at scala.collection.immutable.Map$Map1.apply(Map.scala:114)
	at scribe.Log4JMigration.$anonfun$apply$4(Log4JMigration.scala:70)
	at scala.collection.immutable.List.map(List.scala:286)
	at scribe.Log4JMigration.parse$1(Log4JMigration.scala:70)
	at scribe.Log4JMigration.apply(Log4JMigration.scala:95)
	at scribe.Log4JMigration$.$anonfun$load$3(Log4JMigration.scala:54)
	at scribe.Log4JMigration$.$anonfun$load$3$adapted(Log4JMigration.scala:53)
	at scala.collection.immutable.List.map(List.scala:290)
	at scribe.Log4JMigration$.load(Log4JMigration.scala:53)
	at scribe.Log4JMigration$.load(Log4JMigration.scala:41)
	at scribe.Log4JMigration$.apply(Log4JMigration.scala:35)
	at scribe.Log4JMigration$.load(Log4JMigration.scala:23)
	at moduload.Moduload$.load(Moduload.scala:46)
	at moduload.Moduload$.$anonfun$load$7(Moduload.scala:79)
	at moduload.Moduload$.$anonfun$load$7$adapted(Moduload.scala:79)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at moduload.Moduload$.load(Moduload.scala:79)
	at scribe.Platform$.init(Platform.scala:37)
	at scribe.Logger$.<init>(Logger.scala:256)
	at scribe.Logger$.<clinit>(Logger.scala)
	at scribe.package$.includes(package.scala:25)
	at scribe.package$.log(package.scala:18)
	at scribe.package$.log(package.scala:8)
	at scribe.LoggerSupport.info(LoggerSupport.scala:35)
	at scribe.LoggerSupport.info$(LoggerSuppo

**Comment by darkfrog26** [comment]
I just added some code that should fix it. If you're willing, try pulling the latest from master and publishing locally (`sbt +publishLocal`) to verify this works and I'll get a new release out.

**Comment by aiminguo** [comment]
Thank @darkfrog26 for the quick fix. We had this issue for the spark job launched from yarn cluster only, it used the log4j.properties from hadoop, is there a way to let it use the log4j.properties from spark assembly fat jar file's resource folder?

022.12.21 11:47:53:589 [Driver] INFO c.e.f.u.LoggingSetup.load:23 - Logging Setup initialized successfully: Map(root -> Logger(None,List(LevelFilter(scribe.modify.LevelFilter$$$Lambda$860/549885956@6074bcf7,scribe.modify.LevelFilter$$$Lambda$861/2131718762@d4a1cd8,scribe.Priority@40240000,false,LevelFilter)),List(LogHandlerBuilder(blocks(scribe.format.FormatBlock$Date$Full$@4c991270, RawString( [), scribe.format.FormatBlock$ThreadName$@11687be7, RawString(] ), scribe.format.FormatBlock$Level$@5a9f468d, RawString( ), scribe.format.FormatBlock$$anon$1@2f00f330, RawString( - ), scribe.format.FormatBlock$Messages$@2b0e6e32, scribe.format.FormatBlock$MDCAll$@796b9ff7),scribe.writer.ConsoleWriter$@59600579,scribe.output.format.ASCIIOutputFormat$@71d1e416,List(),scribe.handler.SynchronousLogHandle$@29f66be0)),None,Map(),LoggerId(0)), com.ebay.fireblade.utils -> Logger(Some(LoggerId(3)),List(),List(),None,Map(),LoggerId(4)), com.ebay -> Logger(Some(LoggerId(1)),List(),List(),None,Map(),LoggerId(2)), com -> Logger(Some(LoggerId(0)),List(),List(),None,Map(),LoggerId(1)), com.ebay.fireblade.utils.LoggingSetup -> Logger(Some(LoggerId(4)),List(),List(),None,Map(),LoggerId(5)), com.ebay.fireblade -> Logger(Some(LoggerId(2)),List(),List(),None,Map(),LoggerId(3)))
2022.12.21 11:47:53:618 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.log.dir = .
2022.12.21 11:47:53:618 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.log.file = hadoop.log
2022.12.21 11:47:53:618 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.log.maxbackupindex = 20
2022.12.21 11:47:53:618 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.log.maxfilesize = 256MB
2022.12.21 11:47:53:619 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.mapreduce.jobsummary.log.file = hadoop-mapreduce.jobsummary.log
2022.12.21 11:47:53:619 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.mapreduce.jobsummary.log.maxbackupindex = 20
2022.12.21 11:47:53:619 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.mapreduce.jobsummary.log.maxfilesize = 256MB
2022.12.21 11:47:53:619 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.mapreduce.jobsummary.logger = ${hadoop.root.logger}
2022.12.21 11:47:53:619 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.root.logger = INFO,console
2022.12.21 11:47:53:620 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.security.log.file = SecurityAuth-${user.name}.audit
2022.12.21 11:47:53:620 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.security.log.maxbackupindex = 20
2022.12.21 11:47:53:620 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.security.log.maxfilesize = 256MB
2022.12.21 11:47:53:620 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.security.logger = INFO,NullAppender
2022.12.21 11:47:53:620 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.tasklog.iscleanup = false
2022.12.21 11:47:53:621 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.tasklog.logsRetainHours = 12
2022.12.21 11:47:53:621 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.tasklog.noKeepSplits = 4
2022.12.21 11:47:53:621 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.tasklog.purgeLogSplits = true
2022.12.21 11:47:53:621 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.tasklog.taskid = null
2022.12.21 11:47:53:621 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hadoop.tasklog.totalLogFileSize = 100
2022.12.21 11:47:53:622 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: hdfs.audit.logger = INFO,NullAppender
2022.12.21 11:47:53:622 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.additivity.org.apache.hadoop.hdfs.StateChange = false
2022.12.21 11:47:53:622 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.additivity.org.apache.hadoop.hdfs.server.namenode.FSNamesystem.audit = false
2022.12.21 11:47:53:622 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.additivity.org.apache.hadoop.mapred.AuditLogger = false
2022.12.21 11:47:53:623 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.additivity.org.apache.hadoop.mapred.JobInProgress$JobSummary = false
2022.12.21 11:47:53:623 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.additivity.org.apache.hadoop.yarn.server.resourcemanager.RMAppManager$ApplicationSummary = false
2022.12.21 11:47:53:624 [Driver] WARN scribe.Log4JMigration.apply:78 - Unsupported appender: org.apache.log4j.DailyRollingFileAppender for DRFA
2022.12.21 11:47:53:624 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.DRFA.DatePattern = .yyyy-MM-dd-HH
2022.12.21 11:47:53:624 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.DRFA.File = ${hadoop.log.dir}/${hadoop.log.file}
2022.12.21 11:47:53:624 [Driver] WARN scribe.Log4JMigration.apply:78 - Unsupported appender: org.apache.log4j.DailyRollingFileAppender for DRFAAUDIT
2022.12.21 11:47:53:624 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.DRFAAUDIT.DatePattern = .yyyy-MM-dd-HH
2022.12.21 11:47:53:625 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.DRFAAUDIT.File = ${hadoop.log.dir}/audit/hdfs-audit.log
2022.12.21 11:47:53:625 [Driver] WARN scribe.Log4JMigration.apply:78 - Unsupported appender: org.apache.log4j.DailyRollingFileAppender  for DRFAS
2022.12.21 11:47:53:625 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.DRFAS.DatePattern = .yyyy-MM-dd-HH
2022.12.21 11:47:53:625 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.DRFAS.File = ${hadoop.log.dir}/${hadoop.security.log.file}
2022.12.21 11:47:53:626 [Driver] WARN scribe.Log4JMigration.apply:78 - Unsupported appender: org.apache.hadoop.log.metrics.EventCounter for EventCounter
2022.12.21 11:47:53:626 [Driver] WARN scribe.Log4JMigration.apply:78 - Unsupported appender: org.apache.log4j.RollingFileAppender for JSA
2022.12.21 11:47:53:626 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.JSA.File = ${hadoop.log.dir}/${hadoop.mapreduce.jobsummary.log.file}
2022.12.21 11:47:53:626 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.JSA.MaxBackupIndex = ${hadoop.mapreduce.jobsummary.log.maxbackupindex}
2022.12.21 11:47:53:626 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.JSA.MaxFileSize = ${hadoop.mapreduce.jobsummary.log.maxfilesize}
2022.12.21 11:47:53:627 [Driver] WARN scribe.Log4JMigration.apply:78 - Unsupported appender: org.apache.log4j.RollingFileAppender for MRAUDIT
2022.12.21 11:47:53:627 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.MRAUDIT.File = ${hadoop.log.dir}/mapred-audit.log
2022.12.21 11:47:53:627 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.MRAUDIT.MaxBackupIndex = ${mapred.audit.log.maxbackupindex}
2022.12.21 11:47:53:627 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.MRAUDIT.MaxFileSize = ${mapred.audit.log.maxfilesize}
2022.12.21 11:47:53:627 [Driver] WARN scribe.Log4JMigration.apply:78 - Unsupported appender: org.apache.log4j.varia.NullAppender for NullAppender
2022.12.21 11:47:53:628 [Driver] WARN scribe.Log4JMigration.apply:78 - Unsupported appender: org.apache.log4j.RollingFileAppender for RFA
2022.12.21 11:47:53:628 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.RFA.File = ${hadoop.log.dir}/${hadoop.log.file}
2022.12.21 11:47:53:628 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.RFA.MaxBackupIndex = ${hadoop.log.maxbackupindex}
2022.12.21 11:47:53:628 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.RFA.MaxFileSize = ${hadoop.log.maxfilesize}
2022.12.21 11:47:53:628 [Driver] WARN scribe.Log4JMigration.apply:78 - Unsupported appender: org.apache.log4j.RollingFileAppender  for RFAS
2022.12.21 11:47:53:629 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.RFAS.File = ${hadoop.log.dir}/${hadoop.security.log.file}
2022.12.21 11:47:53:629 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.RFAS.MaxBackupIndex = ${hadoop.security.log.maxbackupindex}
2022.12.21 11:47:53:629 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.RFAS.MaxFileSize = ${hadoop.security.log.maxfilesize}
2022.12.21 11:47:53:629 [Driver] WARN scribe.Log4JMigration.apply:78 - Unsupported appender: org.apache.log4j.RollingFileAppender for RMSUMMARY
2022.12.21 11:47:53:629 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.RMSUMMARY.File = ${hadoop.log.dir}/${yarn.server.resourcemanager.appsummary.log.file}
2022.12.21 11:47:53:630 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.RMSUMMARY.MaxBackupIndex = 20
2022.12.21 11:47:53:630 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.RMSUMMARY.MaxFileSize = 256MB
2022.12.21 11:47:53:630 [Driver] WARN scribe.Log4JMigration.apply:78 - Unsupported appender: org.apache.log4j.DailyRollingFileAppender for SCA
2022.12.21 11:47:53:630 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.SCA.DatePattern = .yyyy-MM-dd-HH
2022.12.21 11:47:53:630 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.SCA.File = ${hadoop.log.dir}/statechange/stateChange.log
2022.12.21 11:47:53:631 [Driver] WARN scribe.Log4JMigration.apply:78 - Unsupported appender: org.apache.hadoop.mapred.TaskLogAppender for TLA
2022.12.21 11:47:53:631 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.TLA.isCleanup = ${hadoop.tasklog.iscleanup}
2022.12.21 11:47:53:632 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.TLA.taskId = ${hadoop.tasklog.taskid}
2022.12.21 11:47:53:632 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.TLA.totalLogFileSize = ${hadoop.tasklog.totalLogFileSize}
2022.12.21 11:47:53:632 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.appender.console.target = System.err
2022.12.21 11:47:53:632 [Driver] WARN scribe.Log4JMigration.apply:106 - Unsupported log4j property: log4j.category.SecurityLogger = ${hadoop.security.logger}
2022.12.21 11:47:53:634 [Driver] ERROR scribe.Log4JMigration.levelFilter:121 - Unsupported level name: ${hadoop.hdfs.statechange.logger}. Continuing with OFF.
2022.12.21 11:47:53:635 [Driver] ERROR scribe.Log4JMigration.levelFilter:121 - Unsupported level name: ${hdfs.audit.logger}. Continuing with OFF.
2022.12.21 11:47:53:635 [Driver] ERROR scribe.Log4JMigration.levelFilter:121 - Unsupported level name: ${mapred.audit.logger}. Continuing with OFF.
2022.12.21 11:47:53:636 [Driver] ERROR scribe.Log4JMigration.levelFilter:121 - Unsupported level name: ${hadoop.mapreduce.jobsummary.logger}. Continuing with OFF.
2022.12.21 11:47:53:636 [Driver] ERROR scribe.Log4JMigration.levelFilter:121 - Unsupported level name: ${yarn.server.resourcemanager.appsummary.logger}. Continuing with OFF.
2022.12.21 11:47:53:637 [Driver] ERROR scribe.Log4JMigration.levelFilter:121 - Unsupported level name: ${hadoop.root.logger}. Continuing with OFF.
2022.12.21 11:47:53:638 [Driver] ERROR scribe.Log4JMigration.error:25 - Error loading Log4JMigrationjava.util.NoSuchElementException: key not found: EventCounter
	at scala.collection.immutable.Map$Map1.apply(Map.scala:114)
	at scribe.Log4JMigration.$anonfun$apply$4(Log4JMigration.scala:70)
	at scala.collection.immutable.List.map(List.scala:286)
	at scribe.Log4JMigration.parse$1(Log4JMigration.scala:70)

**Comment by aiminguo** [comment]
we don't need to migrate the log4j.properties from parent/hadoop level, is there a workaroud to stop loading the log4j.properties? Will Logger.resetRoot achieve it?

**Comment by darkfrog26** [comment]
If you don't include the `Log4JMigration` module in your SBT build (`scribe-migration`) then it won't attempt to load `log4j.properties` at all.

**Comment by darkfrog26** [comment]
@aiminguo I wanted to follow up and make sure you were able to get this resolved?

**Comment by aiminguo** [comment]
@darkfrog26 for the followup, it did resolve the NoSuchElementException (key not found: EventCounter), but the log was turned off with the latest version of 3.10.6, we have to rollback to 3.10.5.

**Comment by darkfrog26** [comment]
@aiminguo let me know if there's something I can do to support the situation better. I'd recommend moving away from the migration tool and just creating your own log configuration as that will give you far better control.
