### ISSUE TITLE
[Suggestion] improve JSON logging usability

### ISSUE THREAD

**Issue by GreyPlane** [outr/scribe#392]
Even though scribe currently has Json logging support, two issues bother me.

- Fabric is a great JSON library, but my codebase already uses Circe intensively, so a pluggable encode/decode implementation seems more adequate for a logging framework.
- There is no reason to lock the logging format, so there should be a pluggable format for JSON logging.

I've implemented my Writer([here is the repo](https://github.com/GreyPlane/scribe-extension)) for addressing these problems, but I want to know if it can be merged into the main framework(which I believe these functionalities should exist), and if it can be, I'm willing to do the necessary work for adjustment and integration.
Or if not, the framework is still flexible enough that meets my demands, so thanks for creating this awesome framework anyway.

**Comment by darkfrog26** [comment]
I have no problem with people using other JSON libraries, I just assumed they'd create their own library to do it since, as it seems to me, the bulk of the code is interacting with the JSON library. Can you clarify the value of a pluggable JSON system over just creating a `scribe-json-circe`?

**Comment by GreyPlane** [comment]
I can make some points, but there is nothing subtle though.

1. If it doesn't exist, you probably end up creating your own Writer for every JSON library, even though it's just one-line code, it just feels more natural to have a common interface and provide a decoder/encoder for every JSON library IMO.
2. From the user's perspective, It feels really weird when I import something named JsonWriter but got a fixed JSON library with it, even though this is probably just a naming issue.

**Comment by darkfrog26** [comment]
I'd welcome a PR if you're interested in this, but by your own statement, it sounds like doing this is actually more code than creating a writer for each JSON library. Another option might be to rename `scribe-json` to `scribe-json-fabric` or something if there are multiple JSON writers. If you can come up with a good way to handle this via interface, I'd welcome it.

**Comment by GreyPlane** [comment]
Ok, I'd like to try to make a good one and propose it this weekend or next.

**Comment by darkfrog26** [comment]
Looking forward to seeing it. Feel free to ping me if you have any questions.
