### ISSUE TITLE
Include ISO8601 datetime formatters in core

### ISSUE THREAD

**Issue by megri** [outr/scribe#401]
The `FormatBlock.Date.Standard` outputs a timestamp in a to me foreign format, such as `2023.02.09 14:25:00`. It would be nice to have an ISO8601-compatible format such as `2023-02-09T14:25:00Z` for easy configuration.

A nice-to-have would be to also have the fractions of seconds configurable, to allow for outputs up to `2023-02-09T14:25:00.123456789Z` for nano-second precision.

If you think this is a good idea I can whip up an initial draft.

**Comment by darkfrog26** [comment]
That would be great. However, I would like to keep the existing date format as the default as it looks a lot cleaner if your only purpose is console output.

**Comment by megri** [comment]
> […] I would like to keep the existing date format as the default […]

Sure, that makes sense for backwards compatibility as well!

I was thinking of adding this at the same level as the `Standard` formatter but naming it something like `IsoTimestamp` or similar. Perhaps with sub-types `IsoTimestamp.<Nano/Micro/Milli/No>Precision`, but I haven't finalised my thoughts on the ergonomics of this.

**Comment by darkfrog26** [comment]
Perhaps even just call it `ISO8601`

**Comment by darkfrog26** [comment]
@megri any updates on this? I'd welcome the PR.

**Comment by megri** [comment]
Hey, been away for some time. Let me check when I get back!

**Comment by megri** [comment]
I'm really sorry for my tardiness. However, it seems you already added something like this in this commit: https://github.com/outr/scribe/commit/d364cfd2c952f17f5201e88c21f790b4cfb822af 😁 

It's simpler than the implementation I had, which looked like this:

```
object ISO8601 extends FormatBlock {
  private lazy val cache = new ThreadLocal[String] {
    override def initialValue(): String = ""
  }
  private lazy val lastValue = new ThreadLocal[Long] {
    override def initialValue(): Long = 0L
  }
  override def format(record: LogRecord): LogOutput = {
    val l = record.timeStamp
    if (l - lastValue.get() > 1000L) {
      val d = s"${l.t.Y}-${l.t.m}-${l.t.d}T${l.t.T}Z"
      cache.set(d)
      lastValue.set(l)
      new TextOutput(d)
    } else {
      new TextOutput(cache.get())
    }
  }
}
```

**Comment by darkfrog26** [comment]
Oh, right! I completely forgot that I added that. :o

Well, thanks for the feedback, and please let me know if you see any other missing features that would improve Scribe.

Going ahead and closing this issue.
