### ISSUE TITLE
Logstash encoding for stdout

### ISSUE THREAD

**Issue by calvinlfer** [outr/scribe#406]
Hello there, 

Is it possible to get logstash encoded logs output to stdout? I see the current implementation takes a remote URL. We already have the infrastructure set u[ to ship our logs from stdout to centralized logging infrastructure.

Thank you
Cal

**Comment by darkfrog26** [comment]
Hi Cal, this shouldn't be a problem. I believe that `classic` Formatter will already work fine to be picked up by LogStash, but you can always create a custom one if it doesn't.  If you do end up having to create a custom Formatter please share it and I'll get it added to the project.

**Comment by darkfrog26** [comment]
Closing for lack of response. Please open a new issue if there's still a problem.
