### ISSUE TITLE
Java 8 time dependency prevents scribe 2.0 usage in android

### ISSUE THREAD

**Issue by fdietze** [outr/scribe#41]
The current android SDK is still on Java 7 and therefore doesn't provide the new Java 8 time library.

**Comment by darkfrog26** [comment]
Ah, that's a problem.  Looks like we need to figure out a better solution than using Java 8's time lib.  I'll think about this more, but I'm very open to suggestions. I wasn't too thrilled with the 1.x solution of using JS Date object, but with a more powerful wrapper, that might be the ideal as it doesn't require any third-party libraries.

**Comment by darkfrog26** [comment]
This was deployed in 2.2.0

**Comment by fdietze** [comment]
Wow, that was quick. Thank you so much!

**Comment by darkfrog26** [comment]
No problem. Let me know if you run into any other problems.
