### ISSUE TITLE
Duplicate date value in package scribe and scribe.format

### ISSUE THREAD

**Issue by cornerman** [outr/scribe#42]
With the new date implementation (:+1:), we have a conflicting symbol `date` in packages `scribe` and `scribe.format`.

This happens when using format and scribe import. There is the `scribe.date` package and the format value `date`:
```
import scribe._
import scribe.format._

val fomatter = formatter"$date bla"
```

Can we do something about this?

**Comment by darkfrog26** [comment]
Yeah, that was a refactoring oversite on my part.  Thanks for pointing it out.

**Comment by darkfrog26** [comment]
In a hurry for this to make it into a release?

**Comment by cornerman** [comment]
Perfect, thank you for fast response. There is no hurry, so no immediate release needed :)

**Comment by darkfrog26** [comment]
This just rolled out in 2.3.0
