### ISSUE TITLE
Unable to have minimumLevel=Info and only enable Trace for certain packages

### ISSUE THREAD

**Issue by andreak** [outr/scribe#425]
This config used to work in 3.8.1:
```scala
package no.officenet.origo.main.web

import scribe.file._
import scribe.file.path.FileNamePart
import scribe.filter.{level => filterLevel, _}
import scribe.format.{Formatter, FormatterInterpolator, dateFull, green, levelColoredPaddedRight, mdc, messages, position, threadName}
import scribe.handler.LogHandler
import scribe.writer.ConsoleWriter
import scribe.{Level, Logger}

import java.nio.file.Paths
import scala.concurrent.ExecutionContext.Implicits.global

object ScribeLogTest {

	val moduleName = "fisk"

	val consoleHandler = LogHandler(minimumLevel = Some(Level.Error), writer = ConsoleWriter)

	val logDir = Paths.get(System.getProperty("user.home"), "visena", "logs", moduleName)

	val fileWriterTrace = FileWriter(
		logDir / ("visena-trace.log")
	).flushAsync

	val fileWriterDebug = FileWriter(
		logDir / ("visena-debug.log")
	).flushAsync

	val selectedInternalPackages = select(
		packageName.startsWith("no.officenet"),
		packageName.startsWith("com.visena")
	)

	val traceHandler = LogHandler(
		writer = fileWriterTrace
		, modifiers =
			List(selectedInternalPackages.include(filterLevel === Level.Trace).excludeUnselected)
	)

	val debugHandler = LogHandler(
		minimumLevel = Some(Level.Debug)
		, writer = fileWriterDebug
	)

	Logger.root
		.clearHandlers()
		.clearModifiers()
		.withMinimumLevel(Level.Info)
		.withHandler(consoleHandler)
		.withHandler(traceHandler)
		.withHandler(debugHandler)
		.replace()

	Logger("no.officenet").withModifier(boosted(Level.Debug, Level.Info)).replace()
	Logger("com.visena").withModifier(boosted(Level.Debug, Level.Info)).replace()

	Logger("com.visena.datasource.dynamic.concurrent").withMinimumLevel(Level.Trace).replace()
	Logger("no.officenet.origo").withMinimumLevel(Level.Trace).replace()

	def main(args: Array[String]): Unit = {
		scribe.error(s"ERROR Kanutt!")
		scribe.info("info")
		scribe.debug(s"Debug")
		scribe.trace(s"Trace!!!")
	}

}
```
It's important to have `.withMinimumLevel(Level.Info)` and only enable trace at the _logger_-level for certain packages. Unless there are many, especially JAVA-libraries, that do time-consuming stuff in `if (logger.isTraceEnabled())`.

The `boosted`-parts would also be easier like this:
```scala
	Logger("no.officenet").withMinimumLevel(Level.Debug).replace()
	Logger("com.visena").withMinimumLevel(Level.Debug).replace()
```
I haven't actually tried this as using `Logger("no.officenet").withModifier(boosted(Level.Debug, Level.Info)).replace()` was recommended at some point, so it's possible this works now.

**Comment by darkfrog26** [comment]
@andreak please see the draft PR referenced.

**Comment by andreak** [comment]
@darkfrog26 Excellent, I'll have a look.

**Comment by darkfrog26** [comment]
@andreak is this not a high priority for you?

**Comment by andreak** [comment]
@darkfrog26 yes it is. Sorry for not addressing this timely. Lots on my plate. Will try tomorrow, tanks for reminding me.

**Comment by darkfrog26** [comment]
No worries, I just take potential bugs in my projects very seriously, so I wanted to make sure we get it sorted. :)

**Comment by andreak** [comment]
This can be closed maybe?

**Comment by andreak** [comment]
I'm not able to get any Trace-logging with `3.11.5` for my example above. Should this work?

**Comment by darkfrog26** [comment]
Can you submit a PR to update https://github.com/outr/scribe/blob/master/core/shared/src/test/scala/specs/LoggingLevelFilteringSpec.scala to reflect what you're trying to accomplish?

**Comment by andreak** [comment]
Sorry, after more testing I made it work.
It seems the bossted (`Logger("no.officenet").withModifier(boosted(Level.Debug, Level.Info)).replace()`) stuff is no longer necessary.

**Comment by darkfrog26** [comment]
Glad to hear it. Let me know if it's not working how you think it should be. I'm happy to dig into this further, I just need clarification of how to reproduce it. :)

**Comment by andreak** [comment]
Let's close this issue as it's working now.
