### ISSUE TITLE
Overriding the path for log files

### ISSUE THREAD

**Issue by lbialy** [outr/scribe#459]
Hi, 

I'm wondering if it's possible (it doesn't look like it is!) to somehow override the path to log files. Current setup always logs to files in (cwd)/logs/app.log/some-log-file.log. I can configure the name of the file, rolling and gzipping just fine, I just can't seem to drop the `/logs/app.log/` part anyhow. I went into sources and I've found out that it's basically hardcoded in PathBuilder:

```
case class PathBuilder(parts: List[PathPart]) {
  def before(writer: FileWriter): Unit = parts.foreach(_.before(writer))
  def after(writer: FileWriter): Unit = parts.foreach(_.after(writer))

  def file(timeStamp: Long): File = {
    val path = parts.foldLeft(PathBuilder.DefaultPath)((previous, part) => part.current(previous, timeStamp)) // << here
    new File(path)
  }

  def iterator(): Iterator[File] = parts
    .foldLeft(Iterator(PathBuilder.DefaultPath))((previous, part) => previous.flatMap(part.all)) // << and here
    .map(new File(_))
 ```
As `PathBuilder.DefaultPath` is defined statically as `lazy val DefaultPath: String = new File("logs", "app.log").getAbsolutePath` I don't see any way to override this. 

Addendum: I am aware that there's PathBuilder.static. I was thinking about a way to provide a path while still using all the FileNamePart niceties like `"run-" % year % "-" % month % "-" % day % "T" % hour % ".log"`. 

Am I missing anything?

**Comment by darkfrog26** [comment]
You can use `PathPart`s to build the path, so if you prefix with `PathPart.Root` you should be able to build an absolute path. Let me know if that doesn't work for you.

**Comment by lbialy** [comment]
I was actually missing something!

The way to get it to work is to use static and `/` method to concatenate stuff.

This worked for me just nice:
```
val fileName    = "run-" % year % "-" % month % "-" % day % "T" % hour % ".log"
val pathBuilder = PathBuilder.static(Paths.get("logs")) / fileName
 ```
 
 Do you accept PRs to documentation?

**Comment by darkfrog26** [comment]
Absolutely! I can use all the help I can get. :)
