### ISSUE TITLE
Help: configure stdout/stderr in function of LogLevel

### ISSUE THREAD

**Issue by david-bouyssie** [outr/scribe#463]
How can I map the stdout/stderr streams to specific log levels?
Ideally I would like to only log errors to stderr and all other log events to stdout.
It doesn't seem to be the default behavior or maybe I did something wrong.

Thanks.

**Comment by darkfrog26** [comment]
You can redirect output from stdout and stderr via https://github.com/outr/scribe/blob/master/core/shared/src/main/scala/scribe/Logger.scala#L188-L197

It used to default to redirect but we found that a lot of people don't want that redirected, so it's a one-liner initialization step.

**Comment by darkfrog26** [comment]
See the configuration options available on that method and let me know if something is missing.

**Comment by david-bouyssie** [comment]
The mentioned method above seem to be a way to use Scribe to redirect then wrap stdout/stderr messages.
What I would like to achieve is in some way similar to what was described there: https://github.com/outr/scribe/issues/272

A trick proposed there consists in using `logger.withHandler(writer = SystemOutWriter)` , but if I do so, I guess that my error messages will be also printed to System.Out. I would like to decide per log level if possible.
Maybe I misunderstood some scribe configuration logic.

**Comment by darkfrog26** [comment]
Oh, sorry for my misunderstanding.

You can do something like:
```scala
logger.withHandler(writer = SystemOutWriter).withModifier(LevelFilter === Level.Error).replace()
```

**Comment by david-bouyssie** [comment]
Thanks. I ended up with this solution:

```scala
scribe.Logger.root.clearHandlers().clearModifiers()
      // Handler for error logging
      .withHandler(
        writer = scribe.writer.SystemErrWriter,
        modifiers = List(
          select(packageName.startsWith(namespace))
            .include(level === Level.Error)
            .excludeUnselected
        )
      // Handler for other log events
      ).withHandler(
        writer = scribe.writer.SystemOutWriter,
        modifiers = List(
          select(packageName.startsWith(namespace))
            .exclude(level === Level.Error)
            .includeUnselected
        )
      ).replace()
```

Does it make sense to you?

**Comment by david-bouyssie** [comment]
It seems it doesn't work properly with this setup, my ERROR messages are sent to stdout.
I guess my modifiers config is incorrect?

**Comment by darkfrog26** [comment]
Let me do some testing to verify and I'll get back to you.

**Comment by darkfrog26** [comment]
The code seems to be working correctly for me:
```scala
package scribe

import scribe.filter._

object Test {
  def main(args: Array[String]): Unit = {
    val namespace = "scribe"
    scribe.Logger.root.clearHandlers().clearModifiers()
//      .withHandler(
//        writer = scribe.writer.SystemErrWriter,
//        modifiers = List(
//          select(packageName.startsWith(namespace))
//            .include(level === Level.Error)
//            .excludeUnselected
//        )
//      )
      .withHandler(
        writer = scribe.writer.SystemOutWriter,
        modifiers = List(
          select(packageName.startsWith(namespace))
            .exclude(level === Level.Error)
            .includeUnselected
        )
      )
      .replace()

    scribe.info("Testing")
    scribe.error("Error test!")
  }
}
```
That only logs the "Testing" message for me.

**Comment by david-bouyssie** [comment]
The configuration I posted previously works like expected.
However, I have found the cause of my issue. I have two locations in my app where I configure scribe:
* one for a given dependency having it own namespace (sqlite4s)
* one at my application level (with a different namespace). This was causing interferences, but only on Scala Native apparently.

I think I have two solutions: configure the dependency logging and app logging in the same place or find a way to do it at two different places.
If I don't use `.clearHandlers().clearModifiers()` can I append independent handlers from different places in my code?
What would you suggest?

**Comment by david-bouyssie** [comment]
Ok thanks.

Is this going to affect only "a.simple" or also all sub-packages like "a.simple.deeply.nested"?

**Comment by darkfrog26** [comment]
Scribe propagates up the packages, so it will apply the modifier at `a.simple` after `a.simple.deeply` and `a.simple.deeply.nested`.

**Comment by david-bouyssie** [comment]
Thanks, I think you can close this issue now.
Last remark, I had to to silent the root Logger to avoid double logging:
```scala
scribe.Logger.root.clearHandlers().clearModifiers().replace()
scribe.Logger("a.simple").withModifier(...).replace()
```
