### ISSUE TITLE
confusing name

### ISSUE THREAD

**Issue by julienledem** [outr/scribe#47]
just FYI:
https://en.wikipedia.org/wiki/Scribe_(log_server)

**Comment by darkfrog26** [comment]
hehe, do you have a better name to suggest? :)

**Comment by julienledem** [comment]
Naming is hard :)
In the past I've made a spreadsheet and got contributors suggest names and vote.
That's how we picked Parquet!
You want to avoid trade marks and existing open source projects so remove those from the list before voting.
Good luck!

**Comment by darkfrog26** [comment]
There's definitely some namespace collision, but it's open-source and at such point it grows enough to be a problem we probably will come up with a new name.

**Comment by cornerman** [comment]
Furthermore, scribe is great name and the linked project seems abandoned :)
