### ISSUE TITLE
NPE when logging with SLF4J and Throwble == null

### ISSUE THREAD

**Issue by andreak** [outr/scribe#479]
The code in `ScribeLoggerAdapter` uses `Some.apply(t)` instead of `Option.apply(t)`, which results in NPE later on.

**Comment by darkfrog26** [comment]
Thanks for this fix. Let me know if you need a new release soon and I'll get a new release out.

**Comment by andreak** [comment]
Yes, please make a release:-)

**Comment by darkfrog26** [comment]
New release `3.11.6` includes this fix.

**Comment by andreak** [comment]
👍
