### ISSUE TITLE
Is it safe to use MDC with cats-effect?

### ISSUE THREAD

**Issue by rolman243** [outr/scribe#506]
I use scribe with cats-effect-3. I want to add at least a trace id to all my logs and I was thinking about using MDC for this. 

Is it safe to use MDC in combination with ce3 as the MDC state has to be saved and restored when execution switches between threads?

**Comment by darkfrog26** [comment]
In Scribe, MDC works differently than other libraries. If you make all of your methods receive an implicit MDC then you can propagate the MDC state across multiple threads easily and it works very well with cats-effect. In the Spice web server there's a good example of this: https://github.com/outr/spice/blob/master/server/src/main/scala/spice/http/server/handler/HttpHandler.scala#L12

**Comment by rolman243** [comment]
Thanks for your reply. I want to avoid using an implicit parameter because I'm developing a library which will be used for multiple business applications. Adding an extra implicit parameter in the library will put a technical implementation detail into the business logic of all applications which will use the lib. I'll keep the implicit parameter solution in mind and try to find another solution.

**Comment by darkfrog26** [comment]
Do you have another idea in mind? I'm happy to expand the functionality of MDC if there's another route that would be better?

**Comment by nimataheri-hootsuite** [comment]
If https://github.com/typelevel/cats-effect/pull/3636 gets merged I believe we can have a `MDCManager` that's backed by a `mdc: IOLocal[MDC]` and we leverage `IOLocals.get` and `IOLocals.set` to implement both of the following methods.

``` scala
trait MDCManager {
  def instance: MDC
  def instance_=(mdc: MDC): Unit
}
```

(only works with `-Dcats.effect.ioLocalPropagation=true`)

**Comment by darkfrog26** [comment]
Very cool! Looking forward to that getting merged.
