### ISSUE TITLE
Allow scribe.fatal

### ISSUE THREAD

**Issue by windymelt** [outr/scribe#566]
I'm using Scribe for production use. I want to show log when fatal situation occurred (e.g. reaching unreachable match, unexpected input, data inconsistency) before shutting down application.

Could you please implement `scribe.fatal` in `scribe.LoggerSupport`? The fatal level seems to be implemented already.

**Comment by darkfrog26** [comment]
Wow, that's a surprising oversight on my part. Yep, I'll get it added.

**Comment by darkfrog26** [comment]
Released with `3.13.2`
