### ISSUE TITLE
Option to exclude "current-date" from FileWriter.daily

### ISSUE THREAD

**Issue by andreak** [outr/scribe#57]
Using FileWriter.daily, the current ("today") logfile's date is part of the filename.
It would be nice to make an option for excluding the date from the current-file. This would make it easier to make existing monitoring-jobs (which today monitors log4j/slf4j files) to continue monitoring the logfiles, without needing to change them.

**Comment by darkfrog26** [comment]
You mean having the current daily log have a consistent filename and at the conclusion of the day it gets renamed to the date stamp?

**Comment by darkfrog26** [comment]
I need to spend a little more time with the `path` functionality anyway.  This is a good idea.  I'll get it added to the current release.

Thanks @andreak

**Comment by andreak** [comment]
Great!

**Comment by darkfrog26** [comment]
@andreak take a look at the re-working of `FileWriter`.  I need to write some tests to make sure everything is happy with the rolling logging, but it offers a much more flexible path and hopefully fulfills all of your needs.

**Comment by andreak** [comment]
Ok, so instead of using .daily() I must use apply() supplying my own implementation of FormattedFileLoggingManager, which takes a custom fileName func where I simply control whether or not to use the millis-value as part of the filename or not?
Works for me.

**Comment by andreak** [comment]
Aha, right.

**Comment by darkfrog26** [comment]
@andreak can you close this ticket once you've confirmed it fulfills your needs?

**Comment by andreak** [comment]
It _looks_ like it'll fulfill my needs, but I have to test with actual rollover, which happens in about 35 min. :-)
I'll close it if all goes well.

**Comment by andreak** [comment]
Works, closing.
