### ISSUE TITLE
How to integrate with scala-play

### ISSUE THREAD

**Issue by mh-trimble** [outr/scribe#584]
Hey I have tried and failed to integrate this with scala play - I got it to the point where it was using scribe from startup, but it would not pick up the configuration (json logging, no colour output) from the beginning and also fall back to multi-line colour logging on fatal exceptions, the most important use case, where you need to rely on good logging.

Here is what I did:

- created a new file `conf/logger-configurator.properties` containing `play.logger.configurator=logger.ScribeLoggerConfigurator`
- created a file `logger/ScribeLoggerConfigurator.scala` with the following content:
```scala
package logger

import org.slf4j.ILoggerFactory
import play.api.Configuration
import play.api.Environment
import play.api.LoggerConfigurator
import play.api.Mode
import scribe.Logger
import scribe.json.ScribeCirceJsonSupport
import scribe.slf4j.ScribeLoggerFactory
import scribe.writer.SystemWriter

import java.io.File
import java.net.URL

class ScribeLoggerConfigurator extends LoggerConfigurator {
  private var factory: ILoggerFactory = _

  override def init(rootPath: File, mode: Mode): Unit = {
    val properties = Map("application.home" -> rootPath.getAbsolutePath)

    configure(properties, None)
  }

  override def shutdown(): Unit = {
    // val context = LogManager.getContext().asInstanceOf[LoggerContext]
    // Configurator.shutdown(context)
  }

  override def configure(env: Environment): Unit = {
    configure(LoggerConfigurator.generateProperties(env, Configuration.empty, Map.empty), None)
  }

  override def configure(
      env: Environment,
      configuration: Configuration,
      optionalProperties: Map[String, String]): Unit = {
    configure(LoggerConfigurator.generateProperties(env, configuration, optionalProperties), None)
  }

  override def configure(properties: Map[String, String], config: Option[URL]): Unit = {
    Logger.root
      .clearHandlers()
      .clearModifiers()
      .withHandler(writer = ScribeCirceJsonSupport.writer(SystemWriter))
      // .withHandler(writer = ConsoleWriter)
      // .withHandler(formatter = logFormatter)
      .replace()
    factory = ScribeLoggerFactory
  }

  override def loggerFactory: ILoggerFactory = factory
}
```
- put `.disablePlugins(PlayLogback)` in my `build.sbt` file in when defining `root`
- imported `scribe` 3.13.4, `scribe-slf4j2`, and `scribe-json-circe`
- and excluded all references to logback
```
excludeDependencies ++= Seq(
  ExclusionRule(
    "ch.qos.logback"
  ),
  ExclusionRule(
    "org.playframework","play-logback_2.13"
  )
)
```
- replaced all old references to scalalogging with scribe logging

**Comment by darkfrog26** [comment]
I fear this is going to be more of an issue to ask the Play folks as Scribe can work as an `slf4j` implementation, `jul`, `System.out/err`, or even a custom override, but I'm not sure how Play actually hooks in.

**Comment by mh-trimble** [comment]
thanks - I'll ask over there

> but I'm not sure how Play actually hooks in.
yeah same here it is not well documented that framework

**Comment by darkfrog26** [comment]
@mh-trimble if you find out it's some problem in Scribe please reopen the ticket and I'm happy to work through it with you.
