### ISSUE TITLE
Weird behaviour using scribe with IOApp.Simple

### ISSUE THREAD

**Issue by mehp** [outr/scribe#654]
The following example prints both "from run" and "from run1", the expectation is it should only print "from run".  Using scala 3.5.1 and scribe 3.15.2

object test extends IOApp.Simple:

    val run = i1
        
    
    val run1 = i2

    def i1 = log.info("from run").pure[IO]
    def i2 = log.info("From run1").pure[IO]

**Comment by mehp** [comment]
not an error.   Wrong code.  val instantiation is calling the logging.

**Comment by darkfrog26** [comment]
@mehp I'm not sure I fully understand the question here, but it sounds like you figured out your problem? Can we close this?

**Comment by mehp** [comment]
Yes please.  It was code error. The logger was getting triggered because it was assigned to a val.  Val variables are instantiated as part of object creation.Thanks & RegardsSriramOn 22 Nov 2024, at 10:52 PM, Matt Hicks ***@***.***> wrote:﻿
@mehp I'm not sure I fully understand the question here, but it sounds like you figured out your problem? Can we close this?

**Comment by darkfrog26** [comment]
No worries. If you have any additional questions, feel free to ask in Discussions.
