### ISSUE TITLE
Rolling FileWriter with maximum size

### ISSUE THREAD

**Issue by cornerman** [outr/scribe#67]
I would like to have a logger which writes to a file but occupies only a fixed maximum size on disk. I just want to keep the most rececent `xxx mb` from these logs.

Can we therefore have a rolling file writer with a maximum bytes per file and maximum number of files setting? Or is this already possible?

**Comment by darkfrog26** [comment]
Though this is technically already possible, it's not easily accomplished.  I'll try to get this handled in a more simplistic way for 2.5.

**Comment by darkfrog26** [comment]
@cornerman, I've done another major refactoring of FileWriter to support a much better level of customization and flexibility.  I'll likely do some additional refactoring in the future to create a builder pattern for more customized solutions, but if you check out `master` you should be able to see it in action.  Please let me know if this fulfills your requirements and I'll get this out in the 2.5.0 release (hopefully next week).

For a simple flat / maximum sized rolling log: https://github.com/outr/scribe/blob/master/core/jvm/src/main/scala/scribe/writer/FileWriter.scala#L59

That supports maximum bytes per file, a maximum number of files, gzip compression of old files, etc.

**Comment by cornerman** [comment]
@darkfrog26 This looks really nice! If I do not enable gzip, it will delete old files right?

Just two question regarding the options:
* `maxLogs` and `maxSize` options for the flat writer: What would happen if I set maxLogs but not maxSize - would this be the same as a simple writer? If this is the case, maybe a `fileRestriction: Option[FileRestriction]` including maximum logs and size could be interesting.
* `gzip` option: Is it right that old files will be gzipped if true and deleted if false?

**Comment by darkfrog26** [comment]
If `maxLogs` is set but `maxSize` is not, then nothing happens for flat.  However, this is applicable for the formatted writer because it will still create new log files even without a `maxSize`.  I'm up for suggestions to make this cleaner...this is just a first pass focusing on functionality more than usage.

The `gzip` option means old log files will be gzipped or just left alone if false.  As soon as the log file changes.  Either through max size or the log file changes (like a daily log file) it will gzip the previous log file.

**Comment by cornerman** [comment]
Ah, got it - will try it out and let you know how it works out. Thanks so much!

**Comment by darkfrog26** [comment]
Please close this after you've had a chance to test if this fulfills all of your needs.  If you have any suggested changes please let me know.

**Comment by darkfrog26** [comment]
@cornerman, any updates on this?  I just finished the major functionality for 2.5 and this is the only blocker left.

**Comment by cornerman** [comment]
@darkfrog26 Sorry for the delay. Finally managed to check it out and works great for this use-case.

One thing I noticed, when I manually deleted a file, the logger did not like it. A `FileNotFoundException` is thrown when trying to rename a non existing file. The app cannot recover from this. Here is a stacktrace:

```
core 1528233255959 AkkaHttpRoute.scala:57 - http -->[response] http:..localhost:12345.api.Api.log(hallo!!!) = Left(InternalServerError) / List(). Took 0.000s.
core 1528233255972 Dsl.scala:71 - Exception in API method: java.nio.file.NoSuchFileException: logs/client-log.log
core java.nio.file.NoSuchFileException: logs/client-log.log
core 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
core 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
core 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
core 	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:409)
core 	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
core 	at java.nio.file.Files.move(Files.java:1395)
core 	at scribe.writer.file.LogFile.rename(LogFile.scala:65)
core 	at scribe.writer.MaxSizePathBuilder.derivePath(MaxSizePathBuilder.scala:17)
core 	at scribe.writer.FileWriter.write(FileWriter.scala:21)
core 	at scribe.handler.SynchronousLogHandler$.$anonfun$log$3(SynchronousLogHandler.scala:25)
core 	at scribe.handler.SynchronousLogHandler$.$anonfun$log$3$adapted(SynchronousLogHandler.scala:24)
core 	at scala.Option.foreach(Option.scala:257)
core 	at scribe.handler.SynchronousLogHandler$.log(SynchronousLogHandler.scala:24)
core 	at scribe.handler.SynchronousLogHandler.log(SynchronousLogHandler.scala:18)
core 	at scribe.Logger.$anonfun$log$4(Logger.scala:41)
core 	at scribe.Logger.$anonfun$log$4$adapted(Logger.scala:41)
core 	at scala.collection.immutable.List.foreach(List.scala:389)
core 	at scribe.Logger.$anonfun$log$3(Logger.scala:41)
core 	at scribe.Logger.$anonfun$log$3$adapted(Logger.scala:40)
core 	at scala.Option.foreach(Option.scala:257)
core 	at scribe.Logger.log(Logger.scala:40)
core 	at wust.backend.ApiImpl.$anonfun$log$1(ApiImpl.scala:163)
core 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
core 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
core 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
core 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
core 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
core 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
core 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
core 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
core 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
core 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
core 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
core 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
core 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
core 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
core 
```

**Comment by cornerman** [comment]
Just a nitpick: Can we maybe rename the parameter `maxSize` in the FileWriter factory to `maxBytes`, because I had to lookup the unit was bytes :)

**Comment by darkfrog26** [comment]
Updated...let me know if those fulfill your needs.

**Comment by cornerman** [comment]
Thank you for the fast update! This is perfect :)
