### ISSUE TITLE
Per call tracing support

### ISSUE THREAD

**Issue by balatbn** [outr/scribe#77]
Scenario: In production, we generally have WARN as log level. However, in case of issues with clients, we want to enable all logs(say DEBUG and above) for a particular client. 

Is it possible to achieve this scribe? Basically can we pass an additional(implicit/normal) flag or traceid to scribe and control the logging?

----

If this is not available by default, any hints on how to implement this in caller(application) code?

**Comment by darkfrog26** [comment]
Can you further clarify what you see this looking like?

**Comment by darkfrog26** [comment]
@balatbn, there are a few ways to accomplish this today in Scribe, but I'm trying to get a better perspective from you how you'd like to see this work to make sure we can accommodate.

You can always define a [LogBooster](https://github.com/outr/scribe/blob/master/core/shared/src/main/scala/scribe/modify/LogBooster.scala) that boosts all logs on a specific path. This can be toggled on/off programmatically.

There are other ways through manipulation of configuration, but if this doesn't do what you need, please clarify what you want and I'm sure we can add it.

**Comment by balatbn** [comment]
To add more, we have done something similar in "olden days"(one thread per request) using log4j MDC. However, in newer async world, it is hard to use MDC for this purpose.

**Comment by darkfrog26** [comment]
To `LogBoost` a single call you can create a custom logger with the booster and use it for when you want a boosted log record.  There are other ways to accomplish that, but that would be the simplest.

I'm still confused what you mean by the `traceId`.  If I understand you correctly, you could create a custom `LogModifier` that checks for `traceId` in MDC (which, in Scribe, supports asynchronous MDC) and boosts the record if it's there?

**Comment by balatbn** [comment]
traceId is just a string client passes(say as part HTTP header). Our idea is something like: If client passes a traceId in a request, enable all debug messages for the call and print it with traceId. Thanks for the details on LogBooster and LogModifier. 

---

w.r.t to MDC, we use http4s as our HTTP framework. So, mostly we don't directly deal with ExecutionContext directly. Sorry, I'm not sure how to integrate with that.

But we'll check LogBooster and LogModifier. Looks like they should solve our problem.

**Comment by darkfrog26** [comment]
@balatbn, I wanted to follow-up with you and see if you were able to get this sorted?  If not, let me know and I'd be happy to help any way I can.

**Comment by balatbn** [comment]
We haven't solved it yet. Looks like we need to write a new Logger. However, we are not quite comfortable with Scala Macros. Still working on it. 

I'll close this for now.

**Comment by darkfrog26** [comment]
@balatbn, I'd be happy to keep working with you on this.  I don't understand why you'd need Macros for it though.  Can you clarify, possibly giving some code samples for what you're trying to do?
