### ISSUE TITLE
how can i disable logging ? 

### ISSUE THREAD

**Issue by chandu0101** [outr/scribe#8]
in prod mode if i want to turn off logging , what needs to be done ?

**Comment by darkfrog26** [comment]
Presuming you want to turn off absolutely all logging:

`Logger.root.clearHandlers()`

If you want to just change the logging level to only log errors you can just define your log handler to do such:

`Logger.root.addHandler(LogHandler(level = Level.Error))`

If there's some other specific scenario you'd like to handle that's not covered let me know.

**Comment by chandu0101** [comment]
`Logger.root.clearHandlers()` is what i want :) ,  thanks for reply.

**Comment by chandu0101** [comment]
@darkfrog26 

I have one more question , with this logic i still pay a method call at runtime(an unit() call!) , probably i'll go with `if(scalajs.LinkingInfo.developmentMode) scribe.info(..)`

**Comment by darkfrog26** [comment]
Yes, there is a very small cost as opposed to other frameworks that compile it out entirely. However, the cost is so small I never expected it was a price not worth paying for the ability to enable debug logging in production without a recompile and restart.

**Comment by darkfrog26** [comment]
I'd be curious if you benchmark the cost at anything higher than nanoseconds.

**Comment by chandu0101** [comment]
>the cost at anything higher than nanoseconds.

agree, but with `scalajs.LinkingInfo.developmentMode` which contant-fold the tree , output file will be smaller!, and its good to eliminate overhead if its possible :)

**Comment by darkfrog26** [comment]
However, unless I'm misunderstanding you, would require re-compiling to re-enable logging whereas the current architecture allows you to enable and disable logging in production on-demand.

**Comment by chandu0101** [comment]
in scala.js - sbt ~fastOptJS => LinkingInfo.developmentMode = true  LinkingInfo.productionMode = false
sbt ~fullOptJS => LinkingInfo.developmentMode = false LinkingInfo.productionMode = true

**Comment by chandu0101** [comment]
https://github.com/jokade/slogging#disable-logging-at-compile-time

**Comment by darkfrog26** [comment]
I think you misunderstand.  For example, in one of my client's production web applications, I have an admin interface that allows me to enable or disable debug logging while the application continues to run.  This comes in handy when I'm experiencing a production issue and am having difficulties reproducing it in dev.  I can enable debug or trace logging while I re-create the scenario or while something specific is occurring on the server to get the information I need, but then I disable it.  This allows me to slightly decrease the performance of my production system for a few minutes to get debug or trace logging without the need to re-compile or even re-start the application.  I'm not opposed to introducing the capacity to exclude logging calls during compilation for those that may want that, but to me that defeats one of the strengths of Scribe.

**Comment by chandu0101** [comment]
>I think you misunderstand.

thats what i thought :( 

> I have an admin interface that allows me to enable or disable debug logging while the application continues to run

you mean ,using some properties on server ? or ..

**Comment by darkfrog26** [comment]
No, the admin interface gives me the capacity to interact graphically with the configuration in real-time so I can make changes to the running application.  In fact, I'm currently building another system based on the same concept for more generic usage (still very early development): https://github.com/outr/uberterm

**Comment by chandu0101** [comment]
oh ok , thanks for info , in my case its a mobile app . I'll vote ` introducing the capacity to exclude logging calls during compilation for those that may want that` 👍

**Comment by darkfrog26** [comment]
I'm fine with it if you'd like to introduce a PR for it.  However, I think the debate is like complaining that your new 8tb hard drive is 5mb smaller than you expected.  It's just such a small amount it really doesn't matter. :)

**Comment by chandu0101** [comment]
haha cool ok :)
