### ISSUE TITLE
Typo in getting started page

### ISSUE THREAD

**Issue by n4to4** [outr/scribe#86]
Just a small typo, but in the [getting started page](https://github.com/outr/scribe/wiki/getting-started#configuring-the-logger),
this `clearHandler` should be `clearHandlers`, I think.

```scala
scribe.Logger.root.clearHandler().clearModifiers().withHandler(minimumLevel = Some(Level.Error)).replace()
```

**Comment by darkfrog26** [comment]
Fixed, thank you. :)
