### ISSUE TITLE
Logging methods takes 0 to 4 args

### ISSUE THREAD

**Issue by darkfrog26** [outr/scribe#87]
Currently, the logging methods take exactly 1 or 2 args (the latter being if an exception is included). With the use of implicits, we could support any organization of those args with separation between.

**Comment by cornerman** [comment]
Can you elaborate how this would be used? I am not sure I understand the description :)

**Comment by darkfrog26** [comment]
Right now it's `def info[M : Loggable](message: => M): Unit`, but I want to support `def info[M1: Loggable, M2: Loggable](message1: => M1, message2: => M2): Unit` etc.

For zero arguments it would allow a blank logging line to be added. I find myself wanting to do that sometimes.  Make more sense?

**Comment by cornerman** [comment]
Ah, that makes sense. So we would then have some default way to concatenate/combine multiple messages in one logline (like we do for adding the exception message)?

**Comment by darkfrog26** [comment]
Yes, exactly!

**Comment by darkfrog26** [comment]
Okay, I've added support for zero arg, but adding more than one value would include significant changes to `LogRecord` and on further reflection, I think that's a bad idea.  LogRecord has the signature `LogRecord[M]` and I'm not prepared to change that at this point.  I may re-evaluate this in 2.7.
