### ISSUE TITLE
Module to support asynchronous traces for cats-effect

### ISSUE THREAD

**Issue by Daenyth** [outr/scribe#95]
Continuing from https://gitter.im/scala/scala?at=5b859436c53ee54c18b6e399

- Support async traces for `cats.effect.IO`
- Ideally support any `F: Effect`

**Comment by darkfrog26** [comment]
@Daenyth, any additional information or insights on this would be appreciated. We can create a `scribe-cats-effect` module to support this.

**Comment by darkfrog26** [comment]
@Daenyth, I'm not very familiar with `cats-effect`. Are you willing to assist with this at all?

**Comment by Daenyth** [comment]
Possibly - I don't really have the time to commit to anything right now

**Comment by ngbinh** [comment]
I am also very interested in this. I am quite familiar with `cats-effect` but not with scribe internal

**Comment by darkfrog26** [comment]
@ngbinh, I am happy to assist either here or on our Gitter channel if you'd like to give it a go.

**Comment by Daenyth** [comment]
The easiest way to implement this will be to fork the module with macros in it, and edit the `log` macro to use `Sync` instead of calling direct methods. The cleaner way would be to implement a macro `Transformer` to take the output of the existing `log` macro and wrap `Sync` around it.

**Comment by darkfrog26** [comment]
Is this purely a performance consideration? I guess I'm a bit confused understanding the benefit of this. Scribe is so fast, that unless you're logging millions of times a second, you shouldn't see any perceptible impact in the performance of the application if you do the regular synchronous logging.  Also, if you don't want that impact, you can always use the built-in async logging.  I don't have any problem with this functionality, I'm just trying to validate that it actually serves a practical purpose.

**Comment by Daenyth** [comment]
No, it's not about performance, it's about the fact that cats-effect uses an M:N threading model where any usage of `ThreadLocal` for data sharing will have broken semantics, because you can't guarantee what parts are writing or reading. Unfortunately this might not be possible, since it probably requires support in the `IO` runtime logic itself, a la monix `TaskLocal`

**Comment by darkfrog26** [comment]
Sorry, I'm not very familiar with `cats-effect`, but I'm happy to help any way I can if you guys want to pursue this further.

**Comment by darkfrog26** [comment]
This is now fully integrated and will be released with Scribe 3.7
