### ISSUE TITLE
Setting minimumLevel < Level.Info does not work

### ISSUE THREAD

**Issue by GRBurst** [outr/scribe#98]
Hey,

I am using scribe version `2.5.3` and calling `scribe.debug()` and `scribe.trace()` does not appear anywhere, although I tried to set the `minimumLevel` is set to `Level.Debug`, `Level.Trace` or `None`.

However, setting t`minimumLevel` to `Level.Warn` excludes `info` messages as expected.

Is this known and probably fixed in `2.6.0`?

Kind regards

**Comment by darkfrog26** [comment]
There was a problem with this previously. Would you mind testing against 2.6 and see if this still occurs?  If it does I can make sure to have a fix quickly.  The 2.5 branch had some issues with a lot of configuration points.

**Comment by fdietze** [comment]
We updated to `2.6.0` and still have the same problem. Any ideas?

**Comment by darkfrog26** [comment]
Can you show the code you have for configuration?

**Comment by fdietze** [comment]
```scala
      Logger.root
        .clearHandlers()
        .withHandler(
          formatter = logFormatter,
          minimumLevel = Some(Level.Debug),
          writer = ConsoleWriter
        )
        .replace()
```

Same behavior for `minimumLevel = None`

**Comment by darkfrog26** [comment]
I was able to reproduce this locally. Investigating now.  I'll let you know when I figure out the problem.

**Comment by darkfrog26** [comment]
Okay, I've found the problem. Not so much a bug as an annoyance. If you change your code to:

```scala
      Logger.root
        .clearHandlers()
        .withHandler(
          formatter = logFormatter,
          minimumLevel = Some(Level.Debug),
          writer = ConsoleWriter
        )
        .replace()
```

**Comment by cornerman** [comment]
@darkfrog26 great, that works. thank you!
