### ISSUE TITLE
Update the wiki for new FileWriterBuilder

### ISSUE THREAD

**Issue by cornerman** [outr/scribe#99]
I cannot make a PR on a Wiki, therefore I make an issue here. In the `getting started` guide, there are examples of how to configure a filewriter (https://github.com/outr/scribe/wiki/getting-started#logging-to-a-file and https://github.com/outr/scribe/wiki/getting-started#logger-by-class).

We should update them to use the new: `FileWriter().path(LogPath.daily())`

**Comment by darkfrog26** [comment]
Updated, thanks man!
